---
output: 
  bookdown::pdf_document2:
    toc: true
    citation_package: natbib
    keep_tex: false
    fig_caption: true
    latex_engine: pdflatex
title: "American Comprehensive Exam Notes"
author: 
- Hao Wang
- Arizona State University
date: '`r format(Sys.Date(), "%B %d, %Y")`'
geometry: margin=1in
fontfamily: mathpazo
fontsize: 12pt
spacing: single
papersize: letter
bibliography: ~/Dropbox/bib/Haowang.bib
biblio-style: apsr
citecolor: blue
header-includes: \usepackage{graphicx, longtable, float, subfigure}
---


\newpage

# POS 530 American Politics

## Week 1 Introduction 

### @Gilens2012 : Affluence and Influence (Book)

**Cite Key** Gilens2012

**Author** Martin Gilens

**Year** 2012

**Summary** 

the association between government policy and public preferences could tell us something important about the responsiveness of our government to the public and the extent to which political influence is reserved for the affluent. Two questions: 1. under which conditions government is responsible 2. Who is among the governed that government respond to. 

The author starts with the discussion of democracy and the citizen-government linkages. While Converse argue that American voters do not have coherent ideology and lacks political understandings, there are several ways that citizens can approach politics without sophisticated knowledge: 1. through cue-taking of the more-knowledgeable citizens. 2. Although democratic participation requires some minimal knowledge, citizens only need to be knowledgeable on some issues, not all of them. 


**Main Findings** 

Policy preference is measured by the actual policy outcomes. The main interest is the association between the policy outcomes and the degree of support expressed by the public/ or a subgroup.

Comparing education and income classes, policy congruence is more salient with the increasing levels of incomes; Interest group is interrelated with income classes. But income is still dominant factor: on economic and tax domain, interest group is closely related with rich people, on social welfare, interest group is evenly distributed across income classes. On gun control and environment, interest group is running against public wishes.




### @Bartels2008 Unequal Democracy

**Cite Key**: Bartels2008 

**Author**: Larry Bartels

**Year**: 2008

**Summary**

The major question of this book is to discuss political equality of a democracy. Economic growth, inequality and political accountability. How to explain the success of the Republican parties if Democrat party helps middle classes so dramatically over the past years? Increasing economic inequality has become a political issue. 

**Findings**

1. Partisan divisions, under R's control, the real income growth for lower and middle income classes has consistently lagged well behind D's administration, also lagged well behind the income growth rates of the rich. Lower unemployment rates under D, but almost identical inflation rates, according to Hibbs 1987

2. Class divisions: Democrats lose support from the middle class and high-income class. However, the general public is not becoming more conservative. Working classes do not value cultural issues more either. (probably race? a US-them division?); Nor did the religious practice a deciding factor.

3. How Rep. can win elections: voters are myopic and only focus on election year performance; 2. Election year income growth for affulent voters is much more consequential, even for low and middle income voters 3. voters are swayed by the balance of compaign spending between incumbents and challengers. 


## Week 2 Congress

### @Sin2014 Separation of Powers and Legislative Organization

**Cite Key** Sin2014

**Author** Gisela Sin

**Year** 2014

**Summary**

The goal is to explain the house rule changes in the Congress. The House majority has to anticipate the actions of Senate and the president, as predetermined by the constitution. Also, the House includes fractions of different goals and interests. Intraparty groups are important for the changes of the House rules as well.  

Gephardt rule abolishment (Rep)

Constituional Constraints: any bills requires approval of both House and Senate as well as the president, or a supermajority of both House and Senate. 

Intraparty conflicts: conservative Rep. and progressive Rep.

Constitutional Theory of Legislative Organization. Environment: by the Constitution, there are three players in determining the policy outcomes: House, Senate and the president. Two stages of game: the power-sharing game and the legislative game. In the power-sharing game, house fractions chooce rules and procedures that distribute power among themselves. In the legislative game, there are two steps, the bicameral agreement stage and the constitutional stage (require all agreements from House, Senate and the President). 


**Findings**

1. House rules changes as the set of constitutional actors changes. Even holding every House member's ideal point constant, a shift in the ideal point of the Senate or the president can change the constitutional set and the available policy choices of the House. 

2. Constitutional set changes predict. Not the change of House median, the party homogeneity, the party polarization, party capacity nor the majority party size. 

3. Centralization happens when the nonspeaker group now get closer to the speaker group, or has ally in Senate/president. Decentralization happens when the Senate and president closer to the speaker fraction/ or when House minority controls both Senate and the president. 

### @Schickler2001: Disjointed Pluralism: Institutional Innovation and the Development of the US Congress

**Cite Key** Schickler2001

**Author** Eric Schickler

**Year** 2011

**Summary**

What explains the institutional changes in Congress? Members have different interests, and different interests are effective at different time periods. 

Pluralism: different coalitions promoting a wide range of collective interests drive processes of change. reelection interest, bolster the capacity, power and prestige of the chamber of Congress as a whole, interest of accessing to the institutional power bases, party-based interest, and policy-based interest. 

Disjointed: the dynamics of institutional development derive from the interactions and tensions among competing coalitions promoting several different interests. 

Predictions:
1. Electoral interests will matter more as member careerism increases
(Mayhew 1974).
2. Congressional capacity and power will be more salient following episodes in which the president has gained influence at Congress's expense (Dodd 1977; Sundquist 1981).
3. Members' interest in institutional power bases will generate pressure
for decentralization following an influx of junior members that
substantially alters the seniority distribution (Dodd 1986; Diermeier 1995).
4. Majority party interests will be particularly important when the majority party is internally unified and has policy preferences that are
sharply different from those of the minority (Rohde 1991).
5. Policy-based interests will generate pressure for institutional changes
when electoral shocks and other exogenous factors substantially
shift the location of the median voter on the floor (Krehbiel 1998;
Schickler 2000).

DV: Institutional changes, include leadership instruments, the committee system, and rules and procedures.  

**Findings**

1890 - 1910: the longest successful era of party government in congressional history, multiple collective interests shaped institutional development. Majority party interest, minority party interest, and concerns about congressional capacity also shaped House rules in 1891-95. 1909-1910 reforms even brought a cross-party coalitions for minority Democrats and insurgent Republicans that was united by a confluence of ideological, partisan, and power base concerns.

1919 - 1932: the House majority party was once again more successful than the Senate majority in promoting interests. GOP majority, the institutional changes initiated by Republicans were at least partly intended to improve the GOP's effectiveness. Cross-party coalitions rooted in ideological and sectoral interests also shaped institutional changes during this period, particularly in the Senate. Even in the House, cross-party coalitions enjoyed notable victories in 1924 and in 1931. In both cases, ideological concerns interacted with members' personal power interests to promote reforms that loosened majority leaders' agenda control.

1937 - 1952: majority party interest receded further in importance. The main collective interests were defending Congress from presidential aggrandizement and promoting the cross-party conservative coalition. e.g.: the Legislative Reorganization Act of 1946, which is due to the congressional-presidential rivalry.

In the 1970s-1980s, party interests returned to prominence, but they interacted with junior members' power base interests and with a renewed concern that Congress had lost too much ground to the executive branch. The result was an array of institutional changes that augmented majority
party influence and helped coordinate spending decisions, but also facilitated entrepreneurship by junior members. 

### @Polsby1968 The Institutionalization of the U.S. House

**Citekey** Polsby1968

**Author** Nelson Polsby

**Year** 1968

**Summary**

Institution: 1. it is relatively well-bounded, different from its environment. 2. The organization is relatively complex, its functions are internally separate on some regular and explicit basis. 3. The organization tends to use universalistic rather than particularistic criteria, and automatic rather than discretionary methods for conducting its internal business. Precedents and rules are followed; merit systems replace favoritism and nepotism; and impersonal codes supplant personal preferences as prescriptions for behavior. 


**Findings**
1. Harder to enter: increased years of members and speakers. 
2. Increased complexity: in the growth in the autonomy and importance of committees, in the growth of specialized agencies of party leadership, and in the general increase in the provision of various emoluments and auxilary aids to members in the form of office space, salaries, allowances, staff aid and committee staffs. 
3. A seniority system is always used.  

### @Hibbing1991 Contours of the Modern Congressional Career

**Citekey** Hibbing1991

**Author** John Hibbing

**Year** 1991

**Summary**
Study changes in four areas: the electoral career, the formal position career, the legislative activity career, and the constituency activity career. 
Changes are standardized. Senior members are more active in rasing issues, but pay less attention to constituencies.

Conclusion: Post-war congressional career electoral support improves; positions within the institution expand ro improve; legislative activity, specialization, and efficiency increase; and attention to district affairs diminishes. Specially, representatives used to do much better electorally as senior members than they were junior members, but now electoral performance is quite similair. Senior members used to axquire quality formal positions only after several terms of service, but now these positions are frequently obtained early in a career. Senior members used to do substantially less constituency service works, but now these differences are slight. Overall, the distinctiveness of particular career stages is much less than it used to be. 


## Week 3 

### @Brooks2013 He Runs She Runs

**Citekey** Brooks2013

**Author** Deborah Jordan Brooks

**Year** 2013

**Summary**

Feminism, women and politics, performance of female politicians etc., are becoming increasingly important in modern democracies. Being systematically discriminated until 20th century, women's political voices are still weaker than males. Unlike Scandinavian countries where female MPs constitute a fairly large percentage (around 30 to 40\%) in the parliaments, there are only about 20 percent females in the Congress. Outside the political arena, females' salaries are significantly lower than males, and there are few female business leaders. Media commentators and journalists keep reminding us that these facts reflect the longstanding gender stereotypes in the United States: females are regarded inferior to males, with respect to politics, female politicians are harder to achieve political success. 

This conventional wisdom becomes the core question of Brooks' book. Gender stereotypes are so prevalently perceived in the public that it is not systematically examined in academia. Confirmation bias states that people tend to find evidence to support their intuition, which helps explain why few scholars asking the question: does gender stereotypes harm female politicians in the same as common females? This book however addresses this issue directly using experimental designs, which are considered more rigorous than non-experimental designs and easier to ensure internal validity.

Two confronting theories are examined in chapter 2. Double Standards Theory holds that female candidates will suffer from the descriptive stereotypes as being women; and they have to balance the potential conflicting identities as being women while acting as leaders; voters have higher standards for female politicians due to the prevailing gender discrimination. In other words, Double Standards Theory reflects the conventional wisdom. The author's argument leans towards the second theory: Leaders-Not-Ladies. This theory holds that being a political leader, female politicians do not suffer from the common gender stereotypes that common females will have. 'Female politicians will be evaluated by voters as 'politician' rather than female' (p. 29). Characteristics on 'good leadership' will outperform 'good femininity'. On the other hand, Brooks argues that female politicians have more information available to voters; and when voter receive more relevant information, stereotypical judgment goes down (p.41).
    

Brooks tests the two hypotheses with experimental methods. Fictional candidates are used rather than the actual political figures. Brooks argues that using fictional roles helps to isolate other confounding characteristics of that candidate which may interact with gender (p.47). On the other hand, experiments provide stronger control over the amount of information that voters will receive. Samples are drawn from YoGov subsample, as the author demonstrates that YoGov is more representative than commonly used student samples. Dependent variables are three questions: overall likeness; competence as a Senator; competence as the President ten years from now. 

The core idea of the experimental design is to examine if voters form different opinions on the two fictional politicians with the same amount of information except for the gender difference. In the six experiments, respondents are required to read the articles with the same content  of the candidates other than the gender. These articles are manipulated across 6 different dimensions: political experience (chapter 4), crying, anger, empathy, and knowledge gaffes (chapters 5 - 7). Analysis is done with ANOVA, which is common in experimental designs (although not widely used in political science). ANOVA outperforms regression in the way that less assumptions are employed and beta coefficients need not to be constant. 

The results support her argument of the Leaders-Not-Ladies. Overall, there is no statistically significant differences between male and female candidates. Instead, female candidates receive positive stereotypes in some aspects like being affirmative; and female politicians are in general regarded more intelligent when both candidates are inexperienced. Female candidates are not penalized particularly for being inexperienced; crying and showing anger; lack of empathy; and for knowledge gaffes. Overall, the results are consistent across different dimensions: female candidates do not suffer from gender stereotypes.   

The experimental designs in this study dramatically enhance the interval validity. Not only in terms of causal inference, but the linkage between theory and experimentation as well. Brooks discusses the key concept of stereotypes in the beginning: `stereotypes allow people to quickly and efficiently - if not always accurately make assumptions about the likely characteristics and behaviors of people' (p.~17). Although she does not emphasize a lot about its theoretical implications, all the later experimentations are based on this very concept. Stereotypes are not necessarily undesirable, people use stereotypes everyday and in most conditions they are useful. For instance, hardcore partisans can vote efficiently on partisan lines even without looking at candidates' proposals. Without enough information and the intention to absorb the information, stereotypes reduce decision-making costs. 

Then the experimental design in the book becomes extremely useful in controlling the amount of information voters receive. Regarding stereotype as a mechanism of efficient opinion formation without sufficient information, there is enough reason to believe that, female politicians who have more exposed information to the public than a common unknown female, may suffer less from gender stereotype. 

Also related to this question, since the information shared by voters will increase with the running campaign, it will be interesting to see if the gender stereotype will diminish when voters know more about the female candidates (or maybe it will be strengthened as perception bias exist before the information processing mechanism, so opinions will skew further with more information). These hypotheses cannot be tested in a one-time design which is performed in this book, but will be available with a panel-tracing survey or multiple experiments with increasing information.

Other than the strength of the book, there are a few points which makes the arguments weaker.
The non-significant findings of gender stereotypes are very robust in different settings (with respect to emotion, experience, empathy, knowledge gaffe), but I am not sure about the effect of gender stimuli. Brooks did mention that about 85% respondents recognize the different names settings correctly, but does this mean the names trigger potential gender stereotypes effectively? 

The other potential flaw comes from the leaders-not-ladies argument. Brooks argues that voters may have different subtypes for female politician as they are playing the leadership position instead of common females. However, on the other hand we see female politicians emphasizing their gender identity in the United States as well as in other countries. According to Hanna Pitkin's representation argument, female politicians have the descriptive representation value of being females, and thus should be expected to interact and communicate with females a lot more. These suggest that albeit voters may regard female politicians differently from the typical gender stereotype, female politicians are still connected with women. Future may focus on the interaction between female politicians as a subtype and the general gender stereotypes. 

Putting electoral contexts into her study, with the absence of partisanship, the experimental designs suffer somewhat from external validity. Partisanship is playing important roles in politics. Some comparative studies show that with stricter partisan disciplines, female MPs are marginalized and cannot form cross-party alliance on women's issues (e.g. Ayata and Tutuncu 2008, Lovenduski 2001). On the other hand, female candidates from Democrats and Republicans seem to have different winning probabilities. Empirical statistics shows more Democratic females in the Congress. Party ID and winning odds for female politicians are worth analyzing in the future. 

Overall, this study uses simulated experimental design to examine the conventional wisdom that female politicians suffer from gender stereotypes. The non-significant results are robust in different experimental settings. The solid evidence from the book strongly challenges conventional wisdom. Also, this study shows how experimental design can help figure out the causal mechanism of opinion formation.  


## Week 4 Congress

### @Burdenetal2014 Sore Loser Laws and Congressional Polarization

**Author** Barry C. Burden and Bradley M. Jones and Michael S. Kang

**Year** 2014

**Summary**
Sore loser law can explain the broadening ideology gaps. It is a constant effect that contribute an additional amount of polarization on top of more general trends.

Sore loser law: a candidate who fails to win a party primary cannot appear on the general election ballots as either an independent candidate or nominee of another party.

How: 1. by removing any subsequent reentry options for candidates, they place greater pressure on primary candidates to cater to the polarized preferences of party bases. 2. by preventing moderate candidates rejected by the party base from getting elected as sore losers. 

Case: 2010 McCain Arizona Senate election: moving to right; 2006 Connecticut reelction, without sore loser law, Lieberman won based on his moderate positions.


**Findings**

Number of states with sore loser laws increased. Polarizing effects of sore loser laws using three sources: congressional candidate surveys, congressional roll-call records, and state legislative measures based on both survey and roll calls. Coding sore loser law as the dummy variable, it is significant. 

### @Druckmanetal2009 Campaign Communications in U.S. Congressional Elections

**Author** James N. Druckman and Martin J. Kifer and Michael Parkin

**Year** 2009

**Summary**
Data is from candidate websites in the three election circles. Key idea is to identify the different compaign strategy adopted by incumbents and challengers. 
Their predictions: 1. challenegers will employ significantly more negative rhetoric and provide more opportunities for voters to engage with campaign 2. challengers will put more emphasis on issues, personal features and party affiliations to distract voters from the incumbency to alternative criteria. 3. Incumbents will emphasize more on experience in public office, familarity, and providing district or state benefits. 

**Findings**
Predictions confirmed. Also challengers are more opt to take risky actions. 

### @Brantonetal2012 Race, Ethnicity, and U.S. House Incumbent Evaluations

**Author** Regina P. Branton and Erin C. Cassese and Bradford S. Jones

**Year** 2012

**Summary**
Consider evaluations of U.S. house incumbents under conditions of racial/ethnic congruence and incongruence. whether different racial groups have ordered preferences among nondescriptive alternatives. 

Descriptive representation: representative possesses an essential attribute linking her to a group whose members also possess that attribute. 

**Findings**
No evidence of race-based judgment among African Americans, while Latinos and Whites demostrates preferences based on race and ethnicity. 

There is a "black-brown divide": competition for political economic resources among minority groups has contributed to intergroup animosities. Black and latinos do not support each other in this study. African American MCs are not the "next best choice" for Latinos. 


### @Krehbriel2000 Party Discipline and Partisanship

**Author** Keith Krehbriel

**Year** 2000

**Journal** AJPS

**Summary**
This article discuss different measurements of partisanship. Current measurement is roll-call vote-based measurement. The author propose a new measurement considering both the preferences of each individual MCs and partisanships. Parties and individual level preferences are considered as exogenous variables, will be considered both in the behavioral stage. 

A spatial cutpoint model: including parties, leadership positions, and minority/majority median voter positions. 

Party-voting score is defined as the percenage of all roll calls in a Congress in which at least a majority of one party votes against at least a majority of the other party. 

Still confused????


### @Krehbiel1993 Where's the Party

**Author** Keith Krehbriel

**Year** 1993

**Journal** BJPS

**Summary**

This article tries to find significant partisan behaviors in the U.S. congress. Question: how to define a significant partisan behavior: legialators of that party vote according to partisan lines in spite of personal disagreement. Test with data from the 99th Congress. Testing significant partisan behaviors independent of personal preferences with the formation of standing committee and the appointment of conferees. Partisan effects are rare. To sum, partisan influences in Congress diminishes.

### @Krehbiel1999 Paradoxes of Parties in Congress

**Author** Keith Krehbriel

**Year** 1999

**Journal** Legislative Studies Quarterly

**Summary**

This article introduces several paradoxes of parties in the congress. 1. Partisan strength: with introparty heterogeneity, partisan strength is not strong. Parties are said to be strong exactly when, viewed through a simple spatial model, they are superfluous. 2. Theories of lawmaking that differ greatly in their party assumptions are often observationally equivalent at the level of predicted outcomes. 3. Party voting occurs even when all legislators ignore completely their partisan identities. Futhermore, party-voting measures are fundamentally incapable of distinguishing between utterly partisan roll-call voting behavior and utterly non-partisan roll-call voting. 

### @HagerTalbert2000 Party Influence on Voting in the House

**Author** Gregory L. Hager and Jeffery C. Talbert

**Year** 2000

**Journal** LSQ

**Summary**

Using roll-call data from the House from the 1950s to 1990s, isolating the effects of parties, including members who switch parties. Regression analysis shows that party influence on voting has varied, but there is an effect, even controling for ideology. DVs are different different levels of party-important votes in Congress. Party shows an effect. On switchers, results show that voting behavior did change after members switched parties.

### @CooperBrady1981 Leadership Style

**Author** Joseph Cooper and David W. Brady

**Year** 1981

**Journal** APSR

**Summary**

A change of leadership style in House. A switch from a hierarchial style to a bargaining parttern. 
They argue that it is the institutional context of the House that determine the leadership power and style. Style and effectiveness are contigent or situational, the impact of leadership style is conditioned on party strength. When strength is high, more hierarchial style, when strength is low, more bargaining style.

**Findings**
A strong correlation between the percentage vote sharing of parties and the centralized leadership style. Leadership style is more determined by institutional context rather than personal traits.

### @Binderetal1999 Uncovering the Hidden Effect of Party

**Author** Sarah A. Binder and Eric D. Lawrence and Forrest Maltzman

**Year** 1999

**Journal** JOP

**Summary**
Reexamining the 1994 'A to Z' discharge petition campaign in the U.S. House of Representatives. a case in which preferences rather than partisanships are said to provide the superior account of legislative behavior. Using the same spatial model which Krehbiel 1995 used, they found significant partisan effect. 

**Findings**

Separating individuals' policy preferences from the partisan labels, they found clear divergence of partisan effects. E.G. NTU (National Taxpayer Union) score, Concord Coaliation score, NOMINATE score...

### @SnyderGroseclose2000 Estimating Party Influence of Roll-Call Voting

**Author** James Snyder and Tim Groseclose

**Year** 2000

**Journal** AJPS

**Summary**
Diffferentiate partisan votings into substansive voting and procedural votings, over the post-war period, party influcence in the House occurs especially often on key procedural votes: the rule on a bill, motions to cut off debate, and motions to recommit. In terms of substantive issues, party influence appears most frequently on budget resolutions, tax policy, social security, social welfare policy, and national debt limit, while it is relatively rare on moral and religious issues and civil rights, and entirely absent on issues such as gun controls. On some issues, such as agriculture, public works, and nuclear energy, party influence has varied dramatically over the period (1871 - 1998).

Definition of a partisan influence: direct pressure applied by the party leader or caucus, including rewards and punishments. 

**Findings**
Evidence from two stage regressions based on monte carlo simulations. Party pressure is vey high in close and very close roll-calls. No major differnce between the House and Senate votings. 


### @CoxMcCubbins1993 Legislative Leviathan

**Author** Gary Cox and Mathew McCubbins

**Year** 1993

**Summary**
This book addresses the role of parties and legislative committees, and the relations between them. Parties in the House, especially the majority parties, are a species of legislative cartel. These cartels serze the power, theoretically resident in the House, to make rules governing the struture and process of legislation. Possession of this rule-making power leads to two main consequences. First, the legislative process in general - and the committee system in particular - is stacked in favor of majority-party interests. Second, because members of the majority party have all the structural advantages, the key players in most legislative deals are members of the majority party and the majority party's central agreements are facilitated by cartel rules and policed by the cartel's leadership. (p.2)

Conditional party government (Rohde 1991): The reforms in the House in the early 1970s and the growth of partisanship in the 1980s are systematically related. Both were the result of important electoral changes, specifically the realignment of democratic constituencies in the South that led to increased intraparty homogeneity. The reforms of the 1970s were proposed by liberal Democrats frustrated by the inability to pass legislation favored by a majority of the rank and file. The reforms created incentives for party leaders to push legislation that reflected the interests of a majority of House Democrats. Following the reforms, further changes in the electorate brought coalitions of representatives that were more similar within parties and more different between them. Both the rules and the intraparty homogeneity brought about by elections set the conditions for strong party government. This book lays out the theory of conditional party government, whereby intraparty homogeneity and interparty heterogeneity determine the extent of partisanship in the House of Representatives.

House committee is not autonomous. It also depends on institutional contexts. 

Majority party has the power to set legislative agenda. Majority party caucus adds another layer of structure and process onto the committee structure studied by Sheplse-Weignast and Weingast-Marshall. The majority party in the House achieves stable policy outcomes by binding members to support a specific structure of agenda power represented by the speaker, the committe chairpersons, and the Rules Committes, a structure which then leads to committees choosing policies that, onaverage, benefit majority party members more than minority party members. 


### @CoxMcCubbins1994 Bonding, Structure, and the Stability of Political Parties: Party Government in the House

**Author** Gary Cox and Mathew McCubbins

**Year** 1994

**Journal** LSQ

**Summary**
The inability of rational choice theory in explaining political prties: the ultimate political rewards are shared by the democratic process of the state. Thus party institutions can be unstable coallition. How to explain the stability of the party system? stability is enforced by extra-legislative organization and bond posting. If a subset of legislators were all bonded by membership in a valuable extralegislative group, such as a political party, and if the cost of giving up the bond were expected to exceed most realistically imaginable benefits from defection, then legisaltors' choices over structure and hence policy might therewith be stabilized. 

Key structural matters: the election of speakers, the design and staffing of the committee system. Caucus members must obey the caucus rules, which include key votes on speaker election, agenda setting rules. Violation will cause an automatic expulsion from the caucus. 

### @SheplseWeignast1984 Political Solutions to Market Problems

**Author** Kenneth Sheplse and Barry Weingast

**Year** 1984

**Journal** APSR

**Summary**
A cost-benefit analysis of the legislative political market. The geographic basis of representation encourages a truncated form of cost-benefit analysis in which the geographic calculation of policy looms large in the politician's calculus. 

Didn't understand this article.

### @Krehbiel1995 Cosponsors and Wafflers from A to Z

**Author** Keith Krehbiel

**Year** 1995

**Journal** AJPS

**Summary**
Theory: A pre-voting, nonpartisan adaptation of Snyder(1991) 'vote-buying' and Groseclose(1995) 'favor-trading' theories implies that significant cosponsorship and discharge-petition behavior will be concentrated in the middle of the ideological spectrum, independent of legislators' partisan affiliations.

Hypotheses: Bill cosponsorship should be a primarily preference-based phenomenon. Waffling -- defined as bill cosponsorship but refusal to sign a discharge petition for the bill -- should be negatively associated with preference extremity and unaffected, at the margin, by majority party membership.

Findings: based on the 103rd House of the A to Z spending plan, results consisitent with the Snyder/Groseclose hypothese, cosponsorship and waffling are explained primarily by preferences, somewhat by membership and money committees, and only slightly by partisanship.


### @Schiller1995 Senators as political entrepreneurs

**Author** Wendy J. Schiller

**Year** 1995

**Journal** AJPS

**Summary**

Using regression analysis and interviews with Sentae legislative staffs, results show that a senator's use of bill sponsorship is a function of institutional and political variables including seniority, proximity of reelection, size of state economy, staff size, committee membership and committee positions. This suggests that Senate is not a place that lacks strcuture and predictability. 

DV is number of bills introduced, positive relations: size of state economy, staff, ideology, number of cimmitte assignment, chair of committee, number of Senators' subcommittee chairs, member of finance committee. Negative: member of foreign relations committee. If differentating between committee bills and noncommittee bills. Committee bills related to variables like chairmanship, subcommittee chairemanship, and membership on finance or Appropriations Committees exert influcen over bills introduced to committees but not to outside committee. Committee bills are influenced by seniority, size of economy, staff, ideology, number of committee assignments, party committee membership etc. 
 
### @Sinclair1992 The Emergence of Strong Leadership in the 1980s House of Representatives 

**Author** Barbara Sinclair

**Year** 1992
  
**Summary**
Compared with the post-World War II leadership style, the 1980s style is more involved in and more decisive in organizing the party and chamber, setting the House agenda, and afftecting legislative outcomes. The study finds that, both over time and cross sectionally, the lieklihood of leadership involvement is greatest when the members most need help and when the costs of the leadership's  providing such help are lowest for majority party members and for the leadership itself and that leadership involvement does increase the probability of legislative success.

### @PattersonCaldeira1988 Party Voting in the United States Congress

**Author** Samuel Patterson and Gregory Caldeira

**Year** 1988

**Journal** BJPS

**Summary**
Partisan polarization in the House of Representatives reponds very sharply to shifts in the magnitude of external party conflict. Party voting in the Senate, by contrast, does not increase with a widening of partisan cleavages in the external environment. The authors believe that it is the staggered terms of senbators insulated them from electoral change in the short run and introduces considerable lags into the relationship between the debate within the party-in-government and the current set of controversies in the party-in-the-electorate. Overall, party voting is much more powerful in the House rather than the Senate. 


### @Krehbiel1990 Congressional Committee Preference Outliers

**Author** Keith Krehbiel

**Year** 1990

**Journal** APSR

**Summary**
The question is whether the standing committe is more extreme than the legislative as a whole. Data is from the 96th to 99th Congress. Measure is interest group ratings of members. Three types of preference outliers in the committee: 1. a classical homogenous high-demand outlier, a committee whose members have a common desire for high levels of benefits from policies within their committee's jurisdiction. e.g. representatives from farming districts dominate agriculture committees and oversee the provision of benefits to their farm constituents. 2. A bipolar outlier: a committee that has significant factions of members on both sides of its policy spectrum. 3. An intense or high-salience outlier is a committee whose members share a uniquely high level of intrinsic interest in the committee, perhaps because its policy domain is highly salient to members' constituents. Results show no significant differences between the standing committee and the legislative as a whole. 

### @JacksonKingdon1992 Ideology, Interest Groups and Legislative Votes

**Author** John Jackson and John Kingdon

**Year** 1992

**Journal** AJPS

**Summary**
The importance of ideology in the government decision making. What explains the legislative decision making? local constituents' economic interest of the legislators' ideological preferences? They critisize the studies that support to show that legislative decisions are the expressions of the personal ideological orientation of the members. They pointed out that the measurement of the ideological preferences, the ADA score, is flawed and lead to an overestimation of statistical results. (ADA: Americans for Democratic Action, an interest group). Using these socres in explaining voting behaviors is a tautology. It is explaining votes with votes. The problem is that, the inerest group score, the explanatory variable, and the votes being modeled, the dependent variable, are almost certain to be tapping the same or related dimensions. 

### @Snyder1992 Committee-Power, Structure-Induced Equilibria, and Roll Call Votes  
 
**Author** James M. Snyder

**Year** 1992

**Journal** AJPS

**Summary**
Concept: structure-induced equilibrium model: equilibria in the model are thus a function not only of legislators' preferences but also of the gatekeeping and monopoly proposal powers possessed by committees. Discussions based on formal model: 1. if some committees are 'preference outliers' relative to the legislature as a whole-- that is, if the median ideal point of the committee members is different from the median ideal point of the whole legislatur -- the  roll-call data are likely to be artifically unidimensional. It is because members will select roll calls on purpose. 2. The unidimensional bias generally persists even as the dimensionallity of the policy space becomes large 3. Even if committes are preference outliers, it may be impossible to discover this fact by looking at only roll call votes. That is, the roll call data may indicate thet committee are 'representative samples' even if they are not.

## Public Opinion

### @BafumiHerron2010 Leapfrog Representation and Extremism

**Author** Joseph Bafumi and Michael Herron

**Year** 2010

**Journal** APSR

**Summary**

The research question the the congruence between voters and preferences of the U.S. legislators. Using an Internet-based, national opinion survey in conjunction with legislator voting records from 109th and 110th Congresses, we show that members of Congress are more extreme than their constituents. We also show that when a congressional legislator is replaced by a new member of the opposite party, one relative extremist is replaced by an opposing extremist (leapfrog representation). We see evidence of leapfrog representation in states and House disstricts in the aggregate as well: the median member of the 109th House was too conservative compared to the median Amercian voter, yet the median member of the 110th Congress was way too liberal compared to the public. The Senate appears to be a more moderate institution whose median member does not move as abruptly as that of the House. 

## On Political Reasoning and Public Opinion

**Question**
Do citizens have stable political reasoning?
No: Zaller, Zaller and Feldman, Converse
Yes: Page and Sahpiro, in a collective sense, public opinion is stable and meaningful, individual level errors will be mitigated by the large number thereom. 
Depends on measures: Achen 1975


Zaller's two models: 1. the political awareness-political predisposition model: predisposition is a readiness sytematically to respond positively or negatively to a class of issue-objects. In this usage, attitudes are the preferences that respondents express about particular courses of public actions, whereas predispositions refer to underlying consistences in response to political choices: opinions about an isue like job programs for blacks are attitudes, ideological sets are examples of predispositions. Political awareness functions as the intermediate channel. 2. The consideration model of attitude construction; predispostion --> considerations <--> situational cues --> attitudes. Considerations are any reason that might induce an individua to decide a political issue one way or the other. The process is through ambivalence deduction. In this model, the situational and dispositional factors are at odds (long-term and short-term causes). 

Snidermanm, Tetlocks and Elms: the situational factor and predispositional factor can be additive, rather than multually exclusive. The flaw of the stop-and-thinking design of Zaller: it is different from an attitude on a position and the reasons for taking that position. 


### @ChongDruckman2010 Dynamic Public Opinion

**Author** Dennis Chong and James Druckman

**Year** 2010

**Journal** APSR

**Summary**

Study the effect of competing messages during campaign. It showed by experiments that comepting messages received at the same time will neutralize each other. However, if received at different time points. Most individuals will give disproportionate wrights to the most recent messages. 

Framing effect: (Druckman 2001, political behavior): when a communication changes people's attitudes toward a object by changing the relative weights thet give to competing considerations about the object. 

Online and memory-based approach: When processed online, individuals routinely intergrate the various considerations contained in the message into an overall issue evaluation. Individuals then store all the summary evaluation in the memory. Possibly forgetting the original considerations that contributed to the tally. When asked subsequently for their attitude toward the issue, individual retrieve and report their overall online tally rather than reconstruct and evaluate the specific pieces of information that comprise this summary (Druckmand Lupia 2000). Individuals who use memory-based model, in contrast, store considerations about the issue in memory without necessarily forming an overall judgment, and subsequently, retrieve and evaluate accessible considertions when asked their poinions about this issue. 

### @ZallerFeldman1992 A Simple Theory of the Survey Response

**Author** John Zaller and Stanley Feldman

**Year** 1981

**Journal** AJPS

**Summary**
Questions: does the survey research reveals stable and true preferences rather than 'making up' answers? 

People have many different, and inconsistent opinions in their minds, when asked, they call to mind a sample of these ideas, including an oversample of ideas made salient by the questionaire and other recent events, and use them to choose among the options offered. But their choices do not, in most cases, reflect anything that can be described as true attitudes; rather, they reflect the thoughts that are most accessible in memory at the moemnt of response. 

Three axioms;

1. Ambivalence. "Most people possess opposing considerations on most issues, that is, considerations that might lead them to decide the issue either way." (585)
2. Response. "Individuals answer survey questions by averaging across the considerations that happen to be salient at the moment of response, where salience is determined by the accessibility axiom."
3. Accessibility: "The accessibility of any given consideration depends on a stochastic sampling process, where considerations that have been recently thought about are somewhat more likely to be sampled." (586)

Method:
The authors administered two types of survey, asking similar questions as in earlier studies. Instead of simply asking the closed-ended response items, though, respondents were asked either to "stop-and-think" (before answering) or reflect (after answering), telling the surveyor what thoughts crossed their mind when thinking about the question. Each thought ("consideration") was coded (number of considerations, number of considerations in each direction, number of explicit expressions of ambivalence, etc.).

### @Zaller1992 The Nature and Origins of Mass Opinion

**Author** John Zaller

**Year** 1992

**Summary**

Opinion is a matter of information and predispostion. Political awareness, political predispositions are the important intervening variables.
The model: 1. Reception axiom: the greater a person's level of cognitive engagement with an issue, the more likely he or she is to be exposed to and comprehend -- in a wordm to receive political messages concerning that issue. 2. Resistence axiom: people tend to resist argument that are inconsistent with their political predispositions, but they do so only to the extent that they possess the contentual information necessary to perceive a relationship between the message and their predispostions (through cueing message). 3. accessibility axiom: the more recently a consideration has been called to mind or thought about, the less time it takes to retrieve that consideration or related considerations from memory and bring them to the top of the head for use. 4. Response asoim: individuals answer survey questions by averaging acriss considerations that are immediately salient or accesible to them. 

In General

Zaller begins by rejecting the view that individuals possess a "true attitude" or single opinion on an issue ("most of what gets measured as public opinion does not exist except in the presence of a pollster" page 265) and instead proposes a model of how individuals construct opinions in response to the particular stimuli that confront them. Zaller's model is constructed from four basic premises:

Individuals differ substantially in their attention to politics and therefore their exposure to elite sources of political information.
People react critically to political communication only to the extent that they are knowledgeable about political affairs.
People rarely have fixed attitudes on specific issues; rather they construct preference statements on the fly as they confront each issue raised.
In constructing these statements, people make the greatest use of ideas that are the most immediately salient to them. Usually these are the ideas that have recently been called to mind or thought about since it takes less time to retrieve these or related considerations from memory and bring them to the top of the head for use.
"Considerations": The 'Receive-Accept-Sample' (RAS) Model

For Zaller, the public forms "considerations" in response to elite discourse (political communications) in the mass media. Often, this discourse consists of multiple, frequently conflicting streams of persuasive messages. In general, the greater an individual's level of political awareness, the more likely she is to receive these messages. Also, the greater a person's level of awareness, the more likely she is to be able, under certain circumstances, to resist (or accept) information that is inconsistent with her basic values or partisanship. If internalized, political considerations become reasons for taking one side rather than the other on a political issue.

When asked their opinions in surveys, people will support or oppose a given policy depending on the mix of positive or negative considerations sampled from the top of the person's mind at the moment of answering a question. Zaller formalizes this in the following manner: 'Prob(Liberal response) = L/(L+C)', where L and C refer to the number of liberal and conservative considerations available in the person's mind. The balance between these considerations depends on society-level variables (such as the intensity and balance of elite discourse) as well as individual-level variables (such as person's political awareness and values).

RAS and Political Awareness

More aware persons will be exposed to more political communications (they 'receive' more), but will be more selective in deciding which communications to internalize as considerations (they 'accept' less). Thus politically aware citizens will tend to fill their minds with large numbers of considerations, and these considerations will tend to be relatively more consistent with one another and with the citizen's predispositions. Less aware citizens will internalize ('receive') fewer considerations and will be less consistent in rejecting ('accepting') them. As a result, more aware people will be more likely to be able to state opinions, and more likely to state opinions that are ideologically consistent with their predispositions.

RAS and Attitude Change: Campaigns and Persuasion

Attitude change (understood as the a change in people's long term response probabilities) results from a change in the mix of ideas to which people are exposed. Changes in the flow of political communication cause attitude change not by producing a sudden conversion experience but by producing gradual changes in the balance of considerations that are present in people's minds and available for answering survey questions.

As has already been indicated, the effects political campaigns (or any elite discourse) vary depending on the relative intensity of the opposing messages and individual's prior stores of partisan information. The least aware are most susceptible to influence in situations in which the information flow is very intense, as in presidential elections (because they 'receive' lots of information but 'accept' almost everything). Moderately aware persons are most susceptible in situations in which messages are moderately intense and partisan orientations activated as in contested House elections, presidential popularity and the later stages of Vietnam. The most aware people are most open to influence when there is little partisan or ideological basis for resistance to persuasion, as in the early stages of a primary campaign, or when there is little access to countervalent information, as in the early stages of the Vietnam War.

Final Comments

According to Zaller, the effects of values and awareness (knowledge) on political attitudes (opinions) are not automatic but depend on elite cues for motivation.

Zaller believes that only the most aware citizens will have a consistent ideology or belief system. According to Zaller, highly aware liberals and conservatives look to appropriate partisan elites to find out "what goes with what." Having acquired this information, they are able to become consistently liberal or consistently conservative across a range of issues. The less aware are less likely to acquire the attitude that is consistently appropriate to their partisan orientation, and hence less likely to develop "attitude constraint" across issues.


Key Definitions

Consideration: Any reason that might induce an individual to decide a political issue one way or another.
Political awareness: An individual's reception and comprehension of communications from the political environment. According to Zaller, political awareness is best measured by simple tests of neutral factual information since factual information is critical for intellectual engagement with politics.
Political predispositions: Stable, individual-level traits that regulate the acceptance or non-acceptance of the political communication the person receives. Predispositions are the critical intervening variable between the communications people encounter in the mass media, on the one side, and their statements of political preference, on the other (since they determine the 'accept' part of the RAS model).
Values: General and enduring standards that hold a more central position than attitudes in individuals' belief systems.


### @Converse2006 The Nature of Belief System in Mass Publics

**Author** Philip E. Converse

**Year** 1964

**Summary**
Most individuals know little about politics and are lack of coherent belief systems. 

Belief systems: as a configuration of ideas and attitudes in which the elements are bound together by some form of constraint or functional interdependence. 'Constraint' may be defined as the success we would have in predicting, given initial knowledge that an individual holds a specified attitude, that he holds certain further ideas and attitudes. 

The declining information for belief system: from elites to the mass public, belief system patterns change a lot: the contextual grasp of 'standard' political belief system fades out very quickly 2. moving from top to bottom of this information dimension, the character of the objects that are central in a belief system changes; from abstract generic to simple and concrete terms. Quite related to education. 

Five different levels: Most people are in the lower levels. 

1. Ideologues: These respondents relied on "a relatively abstract and far reaching conceptual dimension as a yardstick against which political objects and their shifting political significance over time were evaluated" (p.216).
2. Near Ideologues: These respondents mentioned the liberal-conservative dimension peripherally, but did not appear to place much emphasis on it, or used it in a way that led the researchers to question their understanding of the issues.
3. Group Interest: This group did not demonstrate an understanding of the ideological spectrum, but made choices based on which groups they saw the parties representing (e.g. Democrats supporting blacks, Republicans supporting big business or the rich). These people tended to not understand issues that did not clearly benefit the groups they referred to.
4. Nature of the Times: The members of this group exhibited no understanding of the ideological differences between parties, but made their decisions on the "nature of the times." Thus, they did not like Republicans because of the Depression, or they didn't like the Democrats because of the Korean war.
5. No issue content: This group included the respondents whose evaluation of the political scene had "no shred of policy significance whatever" (p. 217). These people included respondents who identified a party affiliation, but had no idea what the party stood for, as well as people who based their decisions on personal qualities of candidates.

Elites have Little Influence on Mass Ideology

Converse also found that the mass public does not seem to share beliefs in any predictable way with elites or that the voting patterns of the people at the lower end of the scale are following the patterns of the ideologues and near ideologues who have a firm grasp of the issues.

Response Instability: Random Changes in Responses

In addition, Converse's interviews with the same respondents over a two-year period often show little correlation with each other. In these cases, only 13 out of 20 managed to locate themselves on the same side of a given controversy in successive interviews. Converse's interpretationis that this change seemed almost exclusively random instead of as a response to changing beliefs.


### @Achen1975 Mass Poltical Attitudes and the Survey Response 

**Author** Christopher Achen

**Year** 1975

**Journal** APSR

**Summary**
Propose an individual's opinion is not a point estimate, rather we should study it as a distribution with means and variations. Two types of instability: variation of attitudes, variation of questions (measurement error). Converse's result of low constraint is partly due to the measurement error, beacause he did not take into consideration of the reliability questions. 'Rather weaj reliabilities for the survey questions were obtained. When the correlation among attitudes were corrected for this unreliability, the result was a shaprly increased estimate of the stability and coherence of voters' political thinking'.


### @Klar2013 The Influence of Competing Identity Primes on Political Preferences

**Author** Smara Klar

**Year** 2013

**Journal** AJPS

**Summary**
People with mutiple group identities may experience different priming effects. For instance a demcoratic mother may support welfare expanding but also worry about the increasing national debt as a parent. 

Identity (Tajfel 1981): an identity can be understood as 'that part of the individuals' self-concept which derives from their knowledge of their memebership of a social group together with the value and emotional significance attached to that membership'.

Three different priming: 1. merely mention the information but no emotional context 2. the efficacy prime not only increase the salience of an identity but also reminds the individual that a large mass of people share an interest that can be addressed by polic, thereby increasing its salience. 3. A threatening appeal increases identity salience by eliciting negative emotions. 

Result: with equal strength in a competing setting, priming does not impact. However, threatening is more effective than efficacy priming in the competing setting.


### @Goren2001 Core Principles and Policy Reasoning in Mass Publics: A Test of Two Theories

**Author** Paul Goren

**Year** 2001

**Journal** BJPS

**Summary**
Question: whether citizens can use core principles in the ideological orientations to decude their policy preferences. The general use theory: everyone draws equally on core principles to determine their preferences. the expertise interaction model: the extent to which core principles influence policy preferences is a function of political expertise. 

Core beliefs: general descriptive beliefs about human nature and society in matters of public affairs. Core values are evaluative standards citizens use to judge alternative social and political arrangements. Political expertise can be defined as the ability to use organized political knowledge stored in long-term memory to process political informaition. 

Variables used as core values and principles:economic individualism, equal opportunity, racial inequality, moral conservatism. Results show support for both models. 


### @Goren2004 Political Sophistication and Policy Reasoning, A Reconsideration

**Author** Paul Goren

**Year** 2004

**Journal** AJPS

**Summary**
A direct response to the sophistification-interaction theory (check @Zaller1992): the strength of the relationship between abstract principles and policy preferrences is conditional on political sophisfication. Analysis of 1984, 1986, 1987, 1988, and 1990 NES data yields two compelling findings: first a series of CFA indicate that beliefs about equal opportunity, self-reliance, and limit government in the social welfare domain and about militarism and anticommunism in the foreign policy domain are structured equivalently in the minds of citizens at different levels of sophistification. Second, SEM shows that political sophistification does not enhance the impact these principles have on policy preferences. 




### @Gorenetal2009 Source Cues, Partisan Identities, and Political Value Expression

**Author** Paul Goren, Christopher Federico and Miki Kittilson

**Year** 2009

**Journal** AJPS

**Summary**
Question: partisan identification and political value expression (equal opportunity, self-reliance, moral traditionalism, and moral tolerance). Through experiments, findings are 1. relationship between individual partisan identities and expressed value support is stronger in the presence of party cues. 2. Out-party (Demo receive Rep) cues are more powerful than in-party cues. 3. these relationships are usually more pronouced among ideologically congruent partisans. 4. party cues promote horizontal constraint among these values. 

### @Gerberetal2010 Personality and Political Attitudes

**Author** Alan S. Gerber and Gregory A. Huber and Conor M. Dowling and Shang E. Ha

**Year** 2010

**Journal** APSR

**Summary**
Personality (five big traits) affect economic and social attitudes differently, and the relationships between Big Five traits and ideology vary substantially between white and black respondents. 

Big Five: Agreeableness, Openness, Emotional Stability, Conscientiousness, and Extraversion. 


### @Druckmanetal2013 Elite Polarization and Public Opinion Formation

**Author** James N. Druckman and Erik Peterson and Rune Slothuus

**Year** 2013

**Journal** APSR

**Summary**

Polarization afftects how citizens think. Specifically, polzarization intensifies the impact of party endorsements on opinions, decreases the impact of substantive information and, perhaps ironically, stimulates greater confidence in those -- less substansively grouded -- opinions. 

Motivated reasoning and partisan motivated reasoning: motivated reasoning is the tendency to seek out information that confirms prior beliefs. Partisan motivated reasoning lead to a situation that partisans will view their party's frame as more effective 



### @ConoverFeldman1981 The Origins and Meaning of Liberal/Conservative Self-Identifications

**Author** Pamela Johnston Conover and Stanley Feldman

**Year** 1988

**Journal** AJPS

**Summary**
Ideology may have different dimensions. Ideology is powerful political symbols to many members of the public. Two types: cognitive (objective information or substantive content associated with this symbol) and evaluative (the affect elicited by the symbol, ability to generate positive and negative feelings). The ideological self-placement is determined directly by the individual's evaluation of the two major ideological labels or groups -- liberals and conservatives. 

Causal chains: from evaluations to ideology self-identification. The ideological spectrum is not bipolar or unidimensional. 

Conservatives and liberals aren't just looking at different sides of the same coin; they're using completely different currencies. Loving conservatives doesn't require hating liberals--it's not bipolar. Rather, we base our evaluations of liberals and conservatives on affective evaluations of symbols (groups, ideas, maybe policies) associated with each group. For example, I evaluate liberals based on my feelings about NARAL, Martin Luther King, and peaceniks; I evaluate conservatives based on my feelings about the NRA, Iraq, and evangelicals. In fact, cognitive (issue-based) evaluations play second fiddle to these symbolic evaluations when I judge each side.


### @Feldman1988 Structure and Consistency in Public Opinion: the Role of Core Beliefs and Values

**Author** Stanley Feldman

**Year** 1988

**Journal** AJPS

**Summary**
Political preferences may be structured by central beliefs and values. Three core values are evaluated here: support for equal opportunity, support for economic individulism, support for free enterprise system. Beliefs of equal opportunity and work ethnic are found to have political influences, belief for free enterprise however is not significant. 





## Framing



### @IyengarKinder1987 News That Matters

**Author** Shanto Iyengar and Donald R. Kinder

**Year** 1987

**Summary**
The media can change our (expressed) opinions without changing our (underlying) attitudes at all, through priming, framing, and agenda setting. Thus, political campaigns don't change our minds; they try to make us think about considerations that will lead us to support one candidate over another. The authors back up their arguments with experimental evidence.

Main Causal Mechanism:
Priming: Affects what you'll have at the top of your head when you make a judgment (see Zaller and Feldman 1992). So if the news covers poor economic performance, then leaps into an analysis of the president's performance, it's primed you to think poorly of the president.
Framing:  media tells you how to think about something. Is it an indigenous rights issue, or an environmentalist story?
Agenda-setting effects: There's a "lead story" effect. If you see prominent place given to unemployment stores (early, long stories in a broadcast), you pay more attention to it. Caveat: Endogeneity. The media tries to select stories that will interest the public. So although the media can set the agenda doesn't mean they necessarily do--it's endogenous.



### @KinderSanders1990 Mimicking Political Debate with Survey Questions: The Case of White Opinion on Affirmative Action for Blacks

**Author** Donald R. Kinder and Lynn M. Sanders

**Year** 1990

**Journal** Social Cognition

**Summary**
This article tests the framing effect of affirmative action. Framing the issue as unfair advantage as opposed to reverse discrimination produced opinions on affirmative action among whites were 1. more coherent with their views on other race policies 2. associated more closely with their opinions on policies but not explicitly, implicating race, such as welfare 3. linked more tightly to negative emotions provoked by preferential treatment 4. more consistent with their general political views 5. more evocative of prejudice and misgivings over equal opportunity 6. less evocative of tangible threaqts that affirmative action might pose to their family and group and of the political principles that affirmative action might violate. These differences suggest that by promoting rival frames, elites may alter how issues are understood and as a consequence, affect what opinions turns out to be.



## Public Opinion and Media

### @Bartels1993 Messages Received

**Author** Larry M. Bartels

**Year** 1993 

**Journal** APSR

**Summary**
In an analysis of opinion change during the 1980 presidential campaign, adjusting for the measurement error, produces mediate media exposure effects, especially for network television news. 

8-month's study during the 1980s presidential campaign. Using Baysian method, after correcting measurement error, somewhat moderate effect of media exposure. THe effect is diminishing among voters with strong prior opinions. It turns out campaign and media exposure are most effective at weak opinioners. 

### @Ansolabehere1994 Does Attack AD Demobilize the Electorate

**Author** Stephen Ansolabehere and Shanto Iyengar and Adman Simon and Nicholas Valentino (AISV)

**Year** 1994

**Journal** APSR

**Summary**
Using an experiment, advertising tone is manipulated within the identical audiovisual context, we find that exposure to negative advertisements dropped intentions to vote by 5%. In the aggregated level campaign of 1992 Senate elections, we show that the demobilizing effects of negative ad are accompanied by a weakened sense of political efficacy. Voters who watch negative ADs become more cynical about the responsiveness of public officials and the electoral process. 

Experiments: 1990 California gubernatorial race, the 1992 California Senate races, and 1993 LS mayor race. Real people, real events. 

The exprimental contents are mostly policy facts statements. 




### @FinkelGeer1998 A Spot Check: Doubt the Demobilizing Effect of Attack AD

**Author** Steven Finkel and John Geer

**Year** 1998

**Journal** AJPS

**Summary**

Theory: Recent research contends that campaign "attack" advertising demobilizes the electorate, with particularly strong effects among political Independents. We dispute this claim, arguing instead that there is little reason to expect a powerful relationship between the tone of campaign advertising and voter turnout. Attack advertising may depress turnout among some voters, but it is likely to stimulate others by increasing their store of political information about the candidates, by increasing the degree to which they care about the election's outcome, or by increasing ties to their party's nominee.

Hypothesis: The amount of a campaign's attack political advertising will be unrelated to overall voter turnout and to turnout among Independents. 

Methods: We employ a multi-method research design, combining a systematic content analysis of presidential campaign advertisements from 1960 to 1992 with aggregate data on turnout and the pooled National Election Studies survey data set. Correlational, linear, and logistic regression analyses are performed. -- use the actual advertisements rather than the newspaper coverage. aggregated level analysis, overall tones; also the individual level data from NES

Results: Controlling for other variables known to influence turnout, we find that attack advertising does not influence either overall turnout rates or individual self-reported votes. Similarly, we find no demobilizing effect for negative advertisements among Independent voters. Further survey analyses show that the effect of attack advertisements on voter withdrawal is weakest among individuals who are most highly attentive to the mass media, and thus who are most likely to have read about or seen the negativity of the campaign.

Why negative ADs may demobilize voters? AISV: three possible explanations: partisan mediation, blank decrease towards both candidates, a decreased political efficacy. 

But negative ADs may also stimulate voting: 1. increased information 2. engaged more in the political information processing 3. provide stronger emotional and affective responses than the positive ones. 


### @KahnKenny1999 Clarifying the Relationship Between Negativity and Participation

**Author** Kim Fridkin Kahn and Patrick J. Kenny

**Year** 1999

**Journal** APSR

**Summary**
Based on U.S. senate campaign, the answer is yes. They found people distinguish between useful information presented in an appropriate manner and irrelevant and harsh mudslinging. As the proportion of legitimate criticisms increases in campaigns, citizens become more likely to cast ballots. When campaigns degenerate into unsubstantiated and shrill attacks, voters tend to stay at home. Also in the individual level, the tone is more consequential for independents, for those with less interest in politics, and for those with less knowledge about politics. 

Data: 1990 NES, tones from candidate campaign and news coverage. Identifying mudslinging races by interviewing campaign managers, who were asked to characterize the opponent's campaign as well as the media's portrayal of both campaigns. 






### @KahnKenny2002 The Slant of the News: How EditorialEndorsements Influence Campaign Coverage and Citizens' Views of Camdidates

**Author** Kim Fridkin Kahn and Patrick J. Kenny

**Year** 2002

**Journal** APSR

**Summary**
We examine newspaper coverage of more than 60 Senatorial campaigns across three election years and find that information on news pages is slated in favor of the candidate endorsed on the newspaper's editorial page. We find that the coverage of incumbent Senators is most affected by these newpaper;s endorsement decision. We xplore the consequences of slanted news coverage by showing that voters evaluate endorsed candidates more favorly than candidates who fail to secure an editorial endorsement. The impact of the endorsement decision on voter's evaluations is most powerful in races receiving a great deal of press attention and among voters who read their local newspaper on a daily base. 





### @Lauetal1999 The Effects of Negative Political Advertisements: A Meta-Analysis Assessment

**Author** Richard R. Lau and Lee Sigelman and Caroline Heldman and Paul Babbitt

**Year** 1999

**Journal** APSR

**Summary**
The data do not support the claim that negative ADs has postitve/megative consequences. 




### @Pageetal1987 What Moves Public Opinions

**Author** Benjamin I. Page and Robert Y. Shapiro and Glenn R. Dempsey

**Year** 1987

**Journal** APSR

**Summary**

Selected 90 pairs of policy questions from the last 15 years that awere repeated within moderate time intervals averaging about three months. Results show that news media paralell opinion changes. 



## Participation and Voting Behaviors

### @Bradyetal1995 Beyond SES: A Resource Model of Political Participation 

**Author** Henry Brady and Sidney Verba and Kay Lehman Schlozman

**Year** 1995

**Journal** APSR

**Summary**
Previous studies have controlled for socioeconomic status variables (income, education, etc) to predict political participation, but they haven't made clear why we should expect these variables to matter. Brady et al turn it around: Why don't people participate in politics? There are three answers: They can't, they don't want to, or nobody asked them to. In other words,

They can't: They lack the time (for participation), civic skills (for involvement), or money (for contributions).
They don't want to: They aren't interested in politics.
Nobody asked: They are isolated from the networks that mobilize people.
Using these independent variables, the authors show why people vote, make donations, or contribute their time to a cause:

Voting: Driven primarily by interest, though civic skills (e.g. education) also matter. Income and time are less important.
Donating money: Driven primarily by income. Neither free time nor civic skills seems to matter.
Spending free time on political activities: Driven by political interest; free time also matters, but civic skills has a greater impact. Income doesn't matter.


### @Lodgeetal1995 Responsive Voter

**Author** Milton Lodge and Marco R. Steenbergen and Shawn Brau

**Year** 1995

**Journal** APSR

**Summary**
Online model of candidate evaluation. Over time people forget most of the campaign information they are exposed to but are nonetheless able to later recollect their summary afftective evaluation of the candidates which they then use to inform their preferences and vote choices. 


### @Desmaraisetal2015 Extended Party Network

**Author** Bruce Desmarais and Ray La Raja and Mike Kowal

**Year** 2015

**Journal** AJPS

**Summary**

In recent years, there has been a re-conceptualization of political parties in the United States.   Rather than think of them as single organizations, scholars have begun to conceive of them as dynamic, dispersed systems of interconnected interest groups.  In other words,  the 'party' is constituted by an extended partisan network (EPN) comprised of groups that do not necessarily carry the label Democrat or Republican. The prevailing theory is that the EPN collectively pursues the functions of traditional party organizations such as selecting and supporting favored candidates for office.

Using network analysis with campaign finance data, we find distinctive communities of groups that converge their political spending on particular challengers.  Moreover, challengers who find themselves in this selective partisan group do substantially better in elections than other challengers even controlling for the overall amount of campaign money they spend.  These findings reveal that conventional accounts of political parties are too simplistic.  Instead, we find that multiple interest groups - along with the traditional party organizations - perform in coordination the tasks we typically associate with political parties.

There are at least two important implications of these findings.  First, by showing that political parties are more than traditional party organizations, we raise a host of questions related to campaign finance reform and other efforts to regulate parties.  If the party is not simply the Democratic or Republican Party committee, then efforts to limit party financing as a way of thwarting corruption are greatly complicated.

Second, our empirical finding provides a plausible explanation for why American parties in Congress do not converge on the preference of median voters (as predicted by Anthony Downs's economic theory of democracy) but instead stay well to the ideological left or right of the vast majority of Americans. Indeed, our findings provide some clues as to why U.S. parties are increasingly polarized ideologically.

### @Bawnetal2012 A Theory of Political Parties

**Author** Kathleen Bawn and Martin Cohen and  David Karol and Seth Masket and Hans Noel and John Zaller

**Year** 2012

**Journal** Perspectives on Politics

**Summary**

The John Aldrich's version: parties are problem solvers and stable coalitions during the legislative process. 

Authors' version: parties are established by policy demanders, in order to make party fullfill the policy goals, interest groups will try to control the nomination process. Citiznes pay little attentions to nomination and interest groups have the highest influence over these process: promote a loyal friend. 

Claims: 1, Policy demanders outside of government form new party coalitions and force change inestablished ones. Policy demanders determine the broad agendas of political conflict. 2. Centrist members of congress are morelikely yo win re-election than extremists, but the former are rare and the latter common in the House. The unnecessary risk borne by most office holders is consistent with our basic notion that policy-demanding groups rather than politicians are the dominant players in parties. 3. When congressional districts and media markets align to conduce more informed electorates, extreme House members are at much greater risk for defeat. This fingding suggests that the extremity of most members of the Congress is not due to voter preferences, but to limitations in the ability of most voters to hold representatives accountable 4. In some cases, interest groups or activists can be shown to determine the particular individuals nominated for office. 


### @KelleyMirer1974 The Simple Act of Voting

**Author** Stanley Kelley and Thad Mirer

**Journal** APSR

**Year** 1974

**Summary**
Voter's decision rule: the voter canvasses his likes and dislikes of the leading candidates and major party involved in an election. Weighing each like and dislike equally, he votes for the candidate toward whom he has the greatest net number of favorable attitudes, if there is such a candidate. If no candidate has such an advantage, the voter votes consistently with his party affiliation, if he has one. If neither condition was meet, the voter made a null decision.


### @Jessee2009 Spatial Voting in the 2004 Presidential Election

**Author** Stephen Jessee

**Year** 2009

**Journal** APSR

**Summary**
The theory of spatial voting has played a large role in the development of important results across many areas of political science. Directly testing the foundational assumptions of spatial voting theory, however, has not been possible with existing data. Using a novel survey design, this article obtains estimates of voter ideology on the same scale as candidate positions. The results of this scaling demonstrate that voters possess meaningful ideologies and, furthermore, that these beliefs are strongly related to the sorts of policy proposals considered in Congress. These ideology estimates are then used to uncover the actual relationships between ideology and vote choice for citizens of various types in the 2004 presidential election. Although the choices of independent voters are shown to be largely consistent with the assumptions of spatial voting theory, the decision rules used by partisans differ strongly from what unbiased spatial voting would imply. Although partisans do converge toward the behavior of independents, and hence toward the assumptions of spatial voting theory, as information levels increase, we see that even highly informed partisans show significant differences from what would be implied by unbiased spatial voting theory.

### @Tomzetal2008 Candidate Positioning and Voter Choice

**Author** Michael Tomz and Robert P. VAN Houweling

**Year** 2008

**Journal** APSR

**Summary**

Three different theories: 1. proximity theory, assumes that citizens prefer candidates whose positions are closest to their own (Downs 1957). 2. Discounting theory: knowing that candidates cannot fully deliver their promises, voters 'discount' campaign pledges and judge each candidate based on the policies they expect the government to adpot if candidate win the office (see Fiorina 1992, Kedar 2005). Discounters may favor candidates unlike themselves if such candidates stand the best chance of producing the most desirable policy outcomes. 3. Directional theory: voters perceive political issues as two sided and want candidates who take their side or direction. This leads to a prediction that voters may want more intense candidates who are in their direction rather than a moderate opponent. 

Method: survey experiments with policy scaled through a list of numbers, results: proximity voting more frequently than discounting and directionary voting.

### @TomzHouweling2009 The Electoral Implications of Candidate Ambiguity

**Author** Michael Tomz and Robert P. Van Houweling

**Year** 2009

**Journal** APSR

**Summary**

Candidates often make ambiguous statements about the policies they intend to pursue. In theory,
ambiguity affects how voters make choices and who wins elections. In practice, measurement and
endogeneity problems have impeded empirical research about the consequences of ambiguity. We conducted survey experiments that overcame these obstacles by manipulating a common form of
ambiguity: the imprecision of candidate positions. Our data show that, on average, ambiguity does not repel and may, in fact, attract voters. In nonpartisan settings, voters who have neutral or positive attitudes toward risk, or who feel uncertain about their own policy preferences, tend to embrace ambiguity. In partisan settings, voters respond even more positively to ambiguity; they optimistically perceive the locations of ambiguous candidates from their own party without pessimistically perceiving the locations of vague candidates from the opposition. We further find, through analysis of two additional new data sets, that candidates often take--and voters frequently perceive--ambiguous positions like the ones in our experiments. The pervasive use of ambiguity in campaigns fits with our experimental finding that ambiguity can be a winning strategy, especially in partisan elections.

# POS598 Political Psychology

## Public Opinion Week

### @Berelson1952 Democratic Theory and Public Opinion

Prerequsite of electorate decisions: 1. a suitable personality structure 2. Interest and participation

Components of electorate decisions: 1. the possession of information and knwoledge 2. Possession of principle: the electorate is required to possess a body of stable political principle or moral standards, in contrast with fluctuating impulses or whims, to which topical questions can be referred for evaluation and decision. 

The process of electorate decision: 1. accurate observation 2. Communication and discussion, the electorate is required to engage in discussion and communication on political affairs. 3. rationality, the electorate is required to exercise rational judgment in political decisions. 

### Adam Bernisky New Directions of Public Opinion

**Year** 2012

**Summary**
Public opinion is a property of individuals, but acquired its power in the public sphere. 

Important review! Read again!

## Self Interest 

### @GreenGerken1989 Self-Interest and Public Opinion Toward Smoking Restrictions and Cigarette Taxes

**Author**  Donald P. Green and Ann Elizabeth Gerken

**Journal** Public Opinion Quarterly

**Year** 1989

**Summary**
Slef-interest has influence over public policies. Data from two random samples of California adults collected by the Field Institute in April 1987 and Februrary 1984 indicate that nonsmokers are far more enthusiastic about tightening smoking restrictions than smokers, although they are very similar in other aspects.

### @KinderKiewiet1979 Economic Discontent and Political Behavior: The Role of Personal Grievances in Economic Judgments in Congressional Voting

**Author** Donald R. Kinder and D. Roderick Kiewiet

**Year** 1979

**Journal** AJPS

**Summary**
Conventional wisdom argues that political decisions are influenced by general economic conditions. This study uses individual level data from 1956 to 1976, showing that voting was not influenced by personal economic grievances. Those voters unhappy with changes in their financial misfortunes showed little inclination to punish candidates of incumbent party. Rather, the voting decision was influenced by judgments regarding recent trends in general business conditions and more powerfully by judgments about the relative competence of the two major parties to manage national economic problems. 

### @JacobShapiro1994 Questioning the Conventional Wisdom of Public Opinion on Health Reform

**Author** Lawrence R. Jacob and Robert Y. Shapiro

**Year** 1994

**Journal** PS: Political Science and Politics

**Summary**
Some questioning points: self-interest or collective interest. Satisfication with own treatment and dissatisfaction towards other people's conditions. Ambivanet attitudes towards taxation; not so opposite attitudes towards government intervention. 

### @Citrinetal1997 Public Opinion Toward Immigration Reform

**Author** Jack Citrin and Donald P. Green and Christopher Muste and Cara Wong

**Year** 1997

**Journal** JOP

**Summary**

This paper tests hypotheses concerning the effects of economic factors on public opinion toward immigration policy. Using the 1992 and 1994 National Election Study surveys, probit models are employed to test diverse conceptualizations of the effects of economic adversity and anxiety on opposition to immigration. The results indicate that personal economic circumstances play little role in opinion formation, but beliefs about the state of the national economy, anxiety over taxes, and generalized feelings about Hispanics and Asians, the major immigrant groups, are significant determinants of restrictionist sentiment. This restricted role of economic motives rooted in one's personal circumstances held true across ethnic groups, among residents in communities with different numbers of foreign-born, and in both 1992 and 1994.

### @Funk2000 The Dual Influence of Self-Interest and Societal Interest in Public Opinion

**Author** Carolyn Funk

**Year** 2000

**Journal** Political Research Quarterly

**Summary**
Measures: self-interest: measured by receiving benefits from the welfare program. Societal interest: measured by the support for equal opportunity index.

Result: citizens use both self-interest and societal interest in evaluating policy proposals. Citizens are not completely selfless, however, citizens seem more willing to engage in self-sacrifice when that sacrifice involves giving over benefits to others than it involves giving up benefits to themselves. 

### @Searsetal1980 Self-Interest vs. Symbolic Policy Attitudes and Presidential Voting

**Author** David O. Sears and Richard R. Lau and Tom R. Tyler and Harris M. Allen

**Journal** APSR

**Year** 1980

**Summary**
This article contrasts short-term self-interest and longstanding symbolic attitudes as determinants of (1) voters' attitudes toward government policy on four controversial issues (unemployment, national health insurance, busing, and law and order), and (2) issue voting concerning those policy areas.In general, we found the various self-interest measures to have very little effect in determining either policy preferences or voting behavior.In contrast,symbolic attitudes (liberal or conservative ideology, party identification, and racial prejudice) had major effects. Nor did self-interest play much of a role in creating "issue public" that were particularly attentive to, informed about, or constrained in their attitudes about these specific policy issues. Conditions that might facilitate more self-interested political attitudes, specifically having privatistic (rather than public-regarding) personal values, perceiving the policy area as a major national problem, being high in political sophistication, perceiving the government as responsive, or having a sense of political efficacy, were also explored,but had no effect.The possibility that some long-term self-interest might be reflected in either group membership or in symbolic attitudes themselves is examined. While such possibilities cannot be definitively rejected, problems with interpreting standard demographic findings as self-interest effects are discussed.

## Personal Experience in Political Thinking

### @Lane1962 Political Ideology

**Summary** 

For most Americans, the events of day-to-day life are morselized, that is, they are not seen as part of a pattern or larger context that lends them political or social significance. 

Some people use their personal experience in interpreting political events (contextualer).

contextualizing and ideologizing: the difference centers on the need to confirm the pattern of ideas employed in this process: if the event is used and needed to support an emotionally involved theory or interpretation, the tendency is toward ideologizing. 'The ideologue takes his cue on the interpretation of information from all sources; the contextualist is more open to information from all sources.'  ideologue takes information selectively. 


### @Mutz1994 Contextualizing Personal Experience: The Role of Mass Media

**Author** Diana C. Mutz

**Year** 1994

**Journal** JOP

**Summary**
Mass media facilitates political thinking by exposing people to similar experiences of others. Besides, mass media coverage can play an especially important role in encouraging presidential accountability for personal problems.

This study considers competing theories concerning the role of mass media in hinderingor facilitating the translation of personal experiences into political preferences. Using national survey and media content data that allow evaluations of both media coverage and individual patterns of media use, this study evaluatesthe influence of mass media on the direct impact of personal experiences on presidential performanceas Ronald Reagan completed his second term in office, and on the indirect impact of personal experiencesby means of their impacton collective-level issue judgments. Exposure to unemployment news appearsto strengthen the impact of personal experienceson presidential performance ratings.Heavy unemployment coverage also increasesthe extent to which perceptionsof national unemployment conditions are generalized from personal experience. Overall, results suggest that mass media may counter the tendency to morselize personal experiences and help legitimize the translation of private interests into political attitudes.


### @Hopkins2010 Local Oppositions to Immigrants

**Author** Daniel Hopkins

**Year** 2010

**Journal** APSR

**Summary**

A politicized places hypothesis: hostile political reations to neighboring immigrants are most likely when communities undergo sudden influxes of immigrants and when salient national rhetoric reinforces the threat. 

Racial threat or power threat: Key (1949) and Blalock (1967): the presence of an outgroup in sufficient numbers will generate competition for scarce resrouces and thus local hostility. 

The politicized places approach assumes that peo ple are highly selective in incorporating environmental information and that information acquisition needs to be explained. 

### @EganMullin2012 Turning Personal Experience into Political Attitude: the effect of local weather on perceptions about global warming

**Author** Patrick J. Egan and Megan Mullin

**Year** 2012

**Journal** JOP

**Summary**

How do people translate their personal experiences into political attitudes? It has been difficult question using observational data, because individuals are typically exposed to experiences in a selective fashion, and self reports of exposure may be biased and unreliable. In this study, we identify one experience to which Americans are exposed nearly at random: their local weather, and show that weather patterns have a significant effect on people's beliefs about the evidence for global warming.

### Lee Ross 1977: Introduction to Attribution Theory and Attribution Error

Attribution theory: native psychology, how ordinary people to understand the causes and implications of the events they witness. 

why a native psychologist model is not sufficient?

## Ideology and values

### @AlvarezBrehm1995 Ameican Ambivalence towards abortion policy

**Author** R. Michael Alvarez and John Brehm

**Year** 1995

**Journal** AJPS

**Summary**

Theory: Using elaboration-likelihood models and insightsfrom the recent core beliefs literature, we show that conflicting core beliefs lead to ambivalence about policy choices.

Hypotheses: Policy choices about abortion are heterogeneous. This heterogeneity across individuals is a functionofthe underlying conflictin their beliefs about the role of women and the sanctityof human life.

Methods: A heteroskedastic probit modelis developedto testthe hypotheses. Results: Heterogeneity is observed for six of seven abortion policy choices; when core values conflict, respondents are more ambivalent in their policy responses and more difficult for our standard models to predict.

Some additional definitions: elaboration likelihood model: the ELM begins with the subject receiving a messsage. The subject elaborates on the message only if he or she is both able and motivated to process the communication. Subjects may have the ability to cognate a message, but lack the motivation. If not motivated, subjects take the message based on the credibility of the speaker. In the standard ELM, the subject in the central model of persuasion subjectively evaluates the message's credibility. When there are multiple conflicting values, there will be larger variance in the subjtect's policy choices. 

### @Jacoby2006 Value Choices and Amercian Public Opinion

**Author** William Jacoby

**Journal** AJPS

**Summary**

Individual preferences among core values are widely believed to be an determinant of political attitudes. Data from the 1994 multi-Investigator Study show that there exists a hierarchical structure of citizens' value preferences. Most people make transitive choices among values and that their value preferences have important influence on issue attitudes. For those make intransitive value choices, this is more due to low levels of political sophistication.

### @HurwitzPeffley1987 A Hierarchical Model of Foreign Policy Attitude

**Author** Jon Hurwitz and Mark Peffley

**Year** 1987

**Journal** APSR

**Summary**

An Information Processing perspective: people are cognitive misers and taking shortcuts whenever it is possible. A complicated and confusing worls requires extensive use of heuristics to render the environemnt interpretable and manageable. 

People use simple heuristic values in reacting to the complicated foreign policy issues. 

A structured view of foreign policy attitudes:
Core values: morality of warfare, ethnocentrism (one country is superior to others)

Mid: Party ID

General Postures: militarism, anti-communism, isolationism

## Parties

### @Campbell1960 The American Voter

**Author** Angus Campbell and Philip E. Converse and Warren E. Miller and Donald E. Stokes

**Year** 1960

**Summary**

Party ID is the major influence on voters' perceptions of political choice as well as their final vote. Party ID is characterized by stability and resistance to contrary influence. Furthermore, it is formed early in life (i.e., it is inherited).


The Funnel Model

Campbell et al. argue that the best predictor (X) of whether an individual will vote Republican or Democratic is the funnel model. The funnel works like this: First, you learn your party ID from parents and socialization. You form a psychological attachment to this party. As such, your partisanship shapes the development of your attitudes; because you like your party, you adopt its positions. Your (underlying) attitudes are then reflected in your positions on the six attitudinal dimensions: the personal attributes of the Democratic candidate (Stevenson), the personal attributes of the Republican (Eisenhower), the groups involved in politics and the questions of group interest affecting them, the issues of domestic policy, the issues of foreign policy, and the comparative record of the two parties in managing the affairs of government. Finally, these issue positions are the proximal cause of your voting decision. In fact, these six issue positions predict voting decisions with 87% accuracy--which is even better than asking voters who they intend to vote for.

Partisan Perception

Not surprisingly, feelings across these six dimensions tend to be highly correlated. For Campbell and his coauthors, this correlation occurs because partisan feelings are strongly shaped by party identification. (Party ID leads to partisan feelings, not the reverse.) In this book, party ID is treated as a psychological force or tie through which voters interpret political issues (each of the aforementioned dimensions). The authors write that "Identification with a party raises a perceptual screen [i.e. selective perception] through which the individual tends to see what is favorable to his partisan orientation." In this sense, the party acts as a supplier of cues by which the individual may evaluate the elements of politics.

Origins of Partisanship

They claim that individuals "inherit" a party ID from their parents and the social milieu in which they are raised and that this party ID is characterized by stability and resistance to contrary influence. (They do recognize that objective events and conditions can lead a voter to modify her party ID or vote against it if her evaluation of the current elements of politics does not agree with her initial allegiances.)

Issues Don't Matter

In their interviews, Campbell et al. find that policies and issues play a small part in most voters' decisions, that only a small fraction of the electorate (12%) displays anything resembling an ideology (i.e., most people when asked about their positions on specific policy issues do not have a consistent pattern of responses in terms of a liberal-conservative dimension), and that voters frequently do not know which party stands for what. These findings cast doubt on the efficacy of voting as a mechanism of democratic control of government.

Changes in Partisanship

Changes in party ID are possible. These changes result from either personal forces (usually changes in an individual's social milieu) or social forces (usually the result of experiences related to great national crises or those experiences related to progress through the life cycle older voters tend to be more conservative).


### @Lavineetal2015 The Ambivalent Partisanship

**Author** Howard G. Lavine and Christopher D. Johnston and Marco R. Steenbergen

**Summary**

Partisanship has be generally regarded as the most important cue for average citizens when forming political opinions and vote choices. As both political scientists and psychologists have recognized, people are busy with their everyday life, and contributing extra effort to political information has literately no personal economic returns to them. As a result, partisanship becomes the economically efficient way for decision-making. On the other hand, the long-lasting pattern of decision-making aligned with the partisan division leads to a concern about biased political opinion and the quality of democratic citizenship. Scholars start to question if average citizens just follow their party disciplines and pay little attention to issue-related policies, or the real politics. Besides, other than the pattern of partisan politics, we are observing a lot of shifts and opinion changes in both opinion polls and electoral results. How to explain these dynamics?

There are citizens who do not always vote according to their parties. They think carefully about issue-related aspects like the objective economic performance, social welfare etc. Lavine's book tackles this question directly by asking who are more likely to go beyond partisan cues and under what conditions will this effort-taking behaviors happen? According to Lavine et al., it is the ambivalent partisanship that leads to these behaviors. 

Partisan ambivalence happens when there is a disconnection between an individual's long-term party identification and short-term party evaluation. For instance, partisan ambivalence may emerge when an individual's party is undergoing a long-stretch of difficulties like splitting ideas, scandals, unsuccessful reforms, or misconduct in international conflicts and domestic emergencies. To address the mechanism of partisan ambivalence, Lavine et al. resort to psychological theories of cognitive process, which are the principles of least effort, sufficiency, and belief perseverance. Least effort relates to the idea that an individual to make minimal effort on their decision making by relying on simple rules like partisan heuristic cues. Based on this principle, party id is often useful as a cognitive shortcut which does not require too much time and effort. Sufficiency is about the confidence of decision making. Party id may not be sufficient in conditions when people are in conflictual situations with their partisan standings. Last, belief perseverance is the motive to make decisions that confirm, rather than contradict, ones system of basic belief and attitudes.


Partisan ambivalence happens when sufficiency principle is not achieved during the cognitive process. Once aroused, ambivalence decreases the cognitive accessibility and perceived reliability of partisan cues, thus motivating citizens to more diagnostic information when making political judgments. Consequently, political judgments are less biased by partisan lens, more accurate and more firmly rooted in normative desirable criteria. 


* Research Design and Results

Lavine et al.'s study relies mostly on survey data from ANES (American National Election Studies) and CCES (Cooperative Congressional Election Study), and is accompanied by three small-scale experimental designs. The key independent variable in the research design is partisan ambivalence, which is measured by both open-ended questions and in-party/out-party attitudes. 

When conceptualizing the ambivalence indicator, they used open-ended questions in the survey. Specifically, they asked respondents to list their favorable and unfavorable thoughts about the party that they support (in-party) and the other party (out-party). Then a following question was asked about the general likeness about in-party and out-party. Ambivalent partisans are then defined as those who score in the 95th percentile in identity-conflicting reactions (good thoughts about the out-party and negative thoughts about the in-party) and the 5th percentile in identity-consistent reactions (good thoughts about in-party and negative thoughts about out-party). Mixed partisans have lower proportions of conflicting identity and higher proportion of consistent identity. Univalent partisans have the highest proportion of consistent identity.

Detailed empirical tests are performed in chapter 4-7. Chapter 4 uses several experiments from multiple sources as well as panel data, showing that ambivalent partisans are less influenced by partisan cues than their univalent peers. Chapter 5 focuses on the accuracy aspect. Using economic perceptions as the example, they demonstrate that ambivalent partisans are more able to form accurate judgment of economic conditions. Besides, unlike the univalent peers, ambivalent partisans are less likely to be influenced by partisan bias. Chapter 6 examine the political participation (esp. voting behaviors). Using 1980-2004 ANES survey data, they found out that ambivalent partisans are not less likely to get involved in political activities. Chapter 7 looks at critical loyalty theory: unlike univalent partisans, ambivalent partisans are more likely to update their party id to reflect the political disagreement. Overall, the authors argue that ambivalent partisans paid more attention to actual policy issues rather than blindly taking the partisan cues; and their perceptions are more responsive and accurate to actual politics. To conclude, ambivalent partisans make better citizens of democracy.  


Overall, this books offers an interesting angle interpreting partisan dynamics in American politics. Scholars have been emphasizing the effect of partisanship and bias in cognition all the way since the very beginning of *The Amercian Voter*. Lavine et al. study this question from a neat aspect by asking who are more (less) likely to be influenced by partisan bias. Their analysis starts with the differentiation of long-term party identity and short-term party evaluation, which can speak directly to SES models as well as retrospective voting behavior literatures (e.g. economic voting). The construction of the concept ambivalence is useful in the sense that it links party id and party evaluation, which allows further analysis when these two aspects are in conflicting situations. The implication of their study applies to a wide variety of researches in information processing and cognition, mass public opinions and even the longitudinal partisan realignment. 

However, I do have some disagreements with the book. My first concern is the argument between ambivalence and partisan influence. As ambivalence is defined in the way when long-term party id is incompatible with short-term party evaluation, a natural inference is that ambivalent partisans are less likely to follow whatever their parties say. And then they demonstrate that partisan influences are diminished among ambivalent individuals. This seems a bit circular reasoning to me. The independent variable (partisan ambivalence) and dependent variable (partisan influence) come from similar reasons and the whole process is endogenous. A corollary of this conceptualization will be: treating partisanship as a group identity, if a group member has some disagreements with the group, we certainly believe that he/she will depreciate group decisions. This is not an interesting implication, what is missing here is who are more likely to have divergent opinions with their group? Lavine et al. did not answer this aspect in their book and they presume the preexistence of `ambivalent partisans', which I think leads to an endogenous problem. 

A related concern on conceptualization is their measurement of ambivalence. They count the numbers of likes and dislikes in the open-ended questions and use this to construct in-party ambivalence. This measurements worsen the endogeneity problem: as likes and dislikes also capture people's emotional reactions to their party other than the disagreeing policy positions. When the unfavorable emotions to parties are aroused, we certainly believe that subjects will be less influenced by their party identifications. 

My second concern of their study is about the temporal dynamics. In the final chapter they conclude that ambivalent partisans are more likely to shift their party id to make it consistent with their beliefs. However, as long as they make the change eventually, will they still be ambivalent partisans as they were, or become a univalent partisan (which according to the authors are not good democratic citizens)? According to their theoretical foundations, partisan cues have the priority of opinion formation as they are efficient and cost-minimizing. As a result these 'former ambivalent' partisans who paid extra effort to form accurate political judgments may resort to partisan cues after switching. However, we believe that they have some personal traits other than 'ambivalence' which makes them be more critical to partisan cues. This aspect as I mentioned in the previous paragraph is not well discussed in their book, which is a potential flaw. 

All in all, I think this book offers many important insights in American politics and political psychology. The introduce of 'ambivalence' is neat and definitely worth further exploration (especially for the conceptualization part). 


### @Fiorina1981 Explorations of a political theory of party identification

The American Voter tradition: party is 'the individual's affective orientation to an important group-object in his environment'. 

Party id is a running tally of retrospective evaluations, as the difference between an individual's past political experiences with the two parties. 



### @Aldrich1995 Why Parties

Aldrichs book seeks to understand the origins and transformation of political parties. Overall, he argues that a political party is an endogenous institution shaped by ambitious political actors. Political parties are the main instruments that 'help' politicians to accomplish their goals (can either be stay in office, certain policy goals and political reputations).

The form in which political parties can 'help' ambitious politicians depends on three variables: the polity (electorate), the institutional setting (for example, a republican form of government,) and the historical context (ideas, values, technological conditions and also path of development). The first two variables create collective action and collective choice problems. The historical context determines whether parties are the most efficient means of solving these two problems.

In sum, parties are designed as attempts to solve problems that current institutional arrangements do not solve and that politicians have come to believe they cannot solve.

Assumptions:

Political parties are created, shaped and transformed by political actors, which are either officeholders, office seekers or benefit seekers.
Voters are not part of the political party, nonetheless they are critical as targets of party activities.
Rational, elective office seekers and holders use the party to achieve their ends. These actors may have values, principles and preferences over policies and means for reaching policy goals. "They also care about office, both for its own sake and for the opportunities to achieve ends that election and reelection made possible", therefore they are concerned with winning. Just as winning elections is a means to other ends for politicians (whether career or policy ends), so too is the political party as a means to these other ends". (21)

The General Argument:

A political party is an endogenous institution shaped by ambitious political actors (office seeker and officeholder). Political parties are the main instruments that "help" politicians to accomplish their goals (long and successful career in political office, achievement of policy ends and power and prestige within the government).

The form in which political parties can "help" ambitious politicians depends on three variables: the polity (electorate), the institutional setting (for example, a republican form of government,) and the historical context (ideas, values, technological conditions and also path of development). The first two variables create collective action and collective choice problems. The historical context determines whether parties are the most efficient means of solving these two problems.

In sum, "parties are designed as attempts to solve problems that current institutional arrangements do not solve and that politicians have come to believe they cannot solve." (22). These problems are related to collective action and collective choice.


### @Bartels2002 Beyond the Running Tally

**Author** Larry Bartels

**Journal** Political Behavior

**Summary**

Bartelss piece examines the impact of long-term partisan loyalties on perceptions of specific political figures and events. In contrast to the notion of partisanship as a simple running tally of political assessments, Bartel shows that party identification is a pervasive dynamic force shaping citizens perceptions of, and reactions to, the political world. In terms of empirical methods, Bartels uses ANES panel data of 1990, 91 and 92. Analysis was conducted with a Bayesian model to capture the dynamics of public opinion change. He also presents more straightforward evidence of contrasts in Democrats and Republicans perceptions of objective politically relevant events. The results show that partisan bias in political perceptions plays a crucial role in perpetuating and reinforcing sharp differences in opinion between Democrats and Republicans.

Bartels piece starts with a critique of the Lodge et al. (1995) 'running tally' argument. Using panel data, he reveals the significant impact of partisanship in information processing. But the time period of the panel data is really short, which decreases the internal validity: is 3 years enough to claim a 'long-term' partisan effect?



### @Greenetal2002 Partisan Hearts and Minds

**Author** Donald P. Green and Bradley Palmquist and Eric Schickler

**Year** 2002

**Summary**

The authors maintain that individuals form partisan attachments early in adulthood and that these political identities, much like religious identities, tend to persist or change only slowly over time. Scandals, recessions, and landslide elections do not greatly affect party identification; large shifts in party attachments occur only when the social imagery of a party changes, as when African Americans became part of the Democratic Party in the South after the passage of the Voting Rights Act. Conclusions are based on a wealth of data analysis using individual-level and aggregate survey data from the United States and abroad.

This study offers a new perspective on party identification: developed in the early childhood and becomes stable afterwards. The stability of partisanship somewhat supports the view that partisan bias and stereotypes exist.

Party ID is based on voters' social identity rather than a rational calculation of policy and claims. 

### @AbramowitzSaunders2006 Exploring the Bases of Partisanship

**Author** Alan I. Abramowitz and Kyle L. Saunders

**Summary**

Party ID is related more to voter's ideological preferences, rather than social group membership claimed by Green, Palmquist and Schickler 2002. Sincethe 1970s, Republican identification has increased substantially among whites inside and outside of the South with the most dramatic gains occurring among married voters, men, and Catholics. Within these subgroups, however, Republican gains have occurred mainly or exclusively among self-identified conservatives. As a result,the relationship between ideology and party identification has increased dramatically. This has important implications for voting behavior. Increased consistency between ideology and party identification has contributed to higher levels of party loyalty in presidential and congressional elections.

## Political Cognition


###@KuklinskiQuirk2000 Reconsidering the Rational Public

**Author** James H. Kuklinski and Paul J. Quirk

**Summary**

Heuristics are not that great, collective public opinion may be irrational as well. We should be cautious about public opinion research. 

From the cognitive psychology perspective, people have 1. policy stereotypes, 2. overconfidence about their political beliefs 3. resistance to correction 4. highly influenced by early arguments. 5. have biased interpretation of messages. 

### Daniel Schacter  1999 Seven Sins of Memory

Transience
Transience refers to the general deterioration of a specific memory over time. Much more can be remembered of recent events than those further in one's past. This is especially true with episodic memory, because every time an episodic memory is recalled, it is re-encoded within the hippocampus, altering the memory each time one recalls it. Transience is caused because of interference. There are two types of interference: proactive interference (old information inhibits the ability to remember new information), and retroactive interference (new information inhibits the ability to remember old information).

Absent-mindedness
This form of memory breakdown involves problems at the point where attention and memory interface. Common errors of this type include misplacing keys or eyeglasses, or forgetting appointments, because at the time of encoding sufficient attention was not paid to what would later need to be recalled.

Blocking
Blocking is when the brain tries to retrieve or encode information, but another memory interferes with it. Blocking is a primary cause of Tip of the tongue phenomenon (a temporary inaccessibility of stored information).

Misattribution
Misattribution entails correct recollection of information with incorrect recollection of the source of that information. For example, a person who witnesses a murder after watching a television program may incorrectly blame the murder on someone he or she saw on the television program. This error has profound consequences in legal systems because of its unacknowledged prevalence and the confidence which is often placed in the person's ability to impart correctly information critical to suspect identification.

Suggestibility
Suggestibility is somewhat similar to misattribution, but with the inclusion of overt suggestion. It is the acceptance of a false suggestion made by others. Memories of the past are often influenced by the manner in which they are recalled, and when subtle emphasis is placed on certain aspects which might seem likely to a specific type of memory, those emphasized aspects are sometimes incorporated into the recollection, whether or not they occurred. For example, a person sees a crime being committed by a redheaded man. Subsequently, after reading in the newspaper that the crime was committed by a brown-haired man, the witness "remembers" a brown-haired man instead of a redheaded man.

Bias
The sin of bias is similar to the sin of suggestibility in that one's current feelings and worldview distort remembrance of past events. This can pertain to specific incidences and the general conception one has of a certain period in one's life. Memories encoded with a certain amount of stimulation and emotion are more easily recalled. Thus, a contented adult might look back with fondness on his or her childhood, induced to do so by positive memories from that time, which might not be representative of his/her average mood during his/her childhood.

Persistence
This failure of the memory system involves the unwanted recall of information that is disturbing. The remembrance can range from a blunder on the job to a truly traumatic experience, and the persistent recall can lead to formation of phobias, post-traumatic stress disorder, and even suicide in particularly disturbing or intrusive instances.

The first three sins involve different types of forgetting, the next three refer to different types of distortions, and the final sin concerns intrusive recollections that are difficult to forget. 

### @Lupia1994 Shortcuts versus Encyclopedias: Information and Voting Behavior in California Insurance Reform Elections


**Author** Arthur Lupia

**Summary**

Voters in mass elections are notorious for their apparent lack of information about relevant political matters. While some scholars argue that an electorate of well-informed voters is necessary for the production of responsive electoral outcomes, others argue that apparently ignorant voters will suffice because they can adapt their behavior to the complexity of electoral choice.To evaluate the validity of these arguments, I develop and analyze a survey of California voters who faced five complicated insurance reform ballot initiatives. I find that access to a particular class of widely available information shortcuts allowed badly informed voters to emulate the behavior of relatively well informed voters. This finding is suggestive of the conditions under which voters who lack encyclopedic information about the content of electoral debates can nevertheless use information shortcuts to vote as though they were well informed.


### @WilsonSchooler1991 Thinking Too Much

**Author** Timothy Wilson and Jonathan Schooler

**Summary**
In Study 1, college students' preferences for different brands of strawberry jams were compared with experts' ratings of the jams. Students who analyzed why they felt the way they did agreed less with the experts than students who did not. In Study 2, college students' preferences for college courses were compared with expert opinion. Some students were asked to analyze reasons; others were asked to evaluate all attributes of all courses. Both kinds of introspection caused people to make choices that, compared with control subjects', corresponded less with expert opinion. Analyzing reasons can focus people's attention on nonoptimal criteria, causing them to base their subsequent choices on these criteria. Evaluating multiple attributes can moderate people's judgments, causing them to discriminate less between the different alternatives.


## Information Process Model

### Elaboration Likelihood Model

**Author** Richard Petty and John Cacioppo

ELM is a dual processing model:

Under the central route, persuasion will likely result from a person's careful and thoughtful consideration of the true merits of the information presented in support of an advocacy. The central route involves a high level of message elaboration in which a great amount of cognition about the arguments are generated by the individual receiving the message. The results of attitude change will be relatively enduring, resistant, and predictive of behavior.

On the other hand, under the peripheral route, persuasion results from a person's association with positive or negative cues in the stimulus or making a simple inference about the merits of the advocated position. The cues received by the individual under the peripheral route are generally unrelated to the logical quality of the stimulus. These cues will involve factors such as the credibility or attractiveness of the sources of the message, or the production quality of the message.[5] The likelihood of elaboration will be determined by an individual's motivation and ability to evaluate the argument being presented.

Central route to persuasion occurs when a person is persuaded by the content of the message. Peripheral route to persuasion occurs when a person is persuaded by something other than the message's content.

### Heuristic-Systematic Model

Shelly Chaiken

Heuristic processing uses judgmental rules known as knowledge structures that are learned and stored in memory. The heuristic approach offers an economic advantage by requiring minimal cognitive effort on the part of the recipient. Heuristic processing is governed by availability, accessibility, and applicability. Availability refers to the knowledge structure, or heuristic, being stored in memory for future use. Accessibility of the heuristic applies to the ability to retrieve the memory for use. Applicability of the heuristic refers to the relevancy of the memory to the judgmental task. Due to the use of knowledge structures, heuristic information processors are likely to agree with messages delivered by experts, or messages that are endorsed by others, without fully processing the semantic content of the message. In comparison to systematic processors, heuristic processors judge the validity of messages by relying more on accessible context information, such as the identity of the source or other non-content cues, which are more persuasive to them than the message characteristics. Heuristic views de-emphasize detailed information processing and focuses on the role of simple rules or cognitive heuristics in mediating persuasion.

Systematic processing involves comprehensive and analytic, cognitive processing of judgment-relevant information. The systematic approach values source reliability and message content, which may exert stronger impact on persuasion, when determining message validity. Judgments developed from systematic processing rely heavily on in-depth treatment of judgment-relevant information and respond accordingly to the semantic content of the message. Recipients developing attitudes from a systematic basis exert considerable cognitive effort and actively attempt to comprehend and evaluate the message's arguments. Systematic recipients also attempt to assess their validity as it relates to the message's conclusion. Systematic views of persuasion emphasize detailed processing of message content and the role of message-based cognitions in mediating opinion change. While recipients utilizing systematic processing rely heavily on message content, source characteristics and other non-content may supplement the recipients' assessment of validity in the persuasion message.


Both heuristic and systematic processes may occur independently. It is also possible for both to occur simultaneously in an additive fashion or in a way that the judgmental implications of one process lend a bias nature to the other. The heuristic-systematic model includes the hypothesis that attitudes developed or changed by utilizing heuristic processing alone will likely be less stable, less resistant to counterarguments, and will be less predictive of subsequent behavior than attitudes developed or changed utilizing systematic processing.
Recipients may sometimes choose to accept message conclusions they might otherwise have correctly rejected, or vice versa, had they properly invested the time and effort needed to receive and scrutinize the message. When the recipient views the argumentation judgment as being inconsequential, the recipient will likely place greater value on economical concerns than reliability concerns.
When economic concerns are predominant, the recipient will likely employ heuristic processing when formulating argumentation judgment. Reliability concerns are influenced by the level of the recipient's issue-involvement or response-involvement.
When reliability concerns are predominant, the recipient will likely employ systematic processing when formulating argumentation judgment. When recipients perceive significant importance in formulating highly accurate argumentation judgment, the recipient will likely employ a systematic processing strategy. Source credibility affects persuasion under conditions of low, but not high, issue-involvement and response-involvement.

### Fazio and Towles-Schwen The MODE Model of Attitude-Behavior Processes

**Author** Russel H. Fazio and Tamara Towles-Schwen

**Summary**
MODE model
This is the theory of attitude evaluation (motivation and opportunity as determinants of the attitude - behavior relation). When both are present, behavior will be deliberate. When one is absent, impact on behavior will be spontaneous. The MODE model was developed by Fazio. A person's attitude can be measured in two different ways:
Explicit measure
Implicit measure

Explicit measure are attitudes at the conscious level, that are deliberately formed and easy to self-report. Implicit measures are attitudes that are at an unconscious level, that are involuntarily formed and are typically unknown to us.[29] Both explicit and implicit attitudes can shape an individual's behavior. Implicit attitudes, however, are most likely to affect behavior when the demands are steep and an individual feels stressed or distracted.

### @HaugtvedtPetty1992 Personality and Persuasion: Need for Cognition

**Author** Curtis P. Haugtvedt and Richard E. Petty

**Summary**

Hypotheses about the persistence and resistance of attitudes and beliefs formed by individuals scoring high or low in Need for Cognition (NC; Cacioppo & Petty, 1982) were derived from the Elaboration Likelihood Model of persuasion (Petty & Cacioppo, 1986). In Study 1, both high-NC and low-NC individuals formed evaluatively similar attitudes toward an unfamiliar attitude object (a new product) after exposure to a persuasive message (an advertisement). The newly formed attitudes of high-NC individuals decayed less than the newly formed attitudes of low-NC individuals over a 2-day period. In Study 2, both high-NC and low-NC individuals were persuaded by an initial message that a food additive was unsafe. However, when immediately exposed to a second countermessage arguing that the product was safe, the initial experimentally created beliefs of high-NC individuals were shown to be more resistant to change than the experimentally created beliefs of low-NC individuals.

## Emotions and automaticity

### @Mackuenetal2007 The Theory of Affective Intelligence in American Democracy

**Author** Michael Mackuen and George E. Marcus and W. Russell Neuman and Luke Keele

**Year** 2007

**Summary**


AIT argues that the Normal Vote Model and the Rational Choice Model have both gotten something right, but share a similar error by taking a special case of political judgment and treating it as if it were the general case. How can it be that the Normal Vote and Rational Choice models are special cases, that is, theoretical specifications that apply only in some rather than in all circumstances? The two established theories presume that voters have invariant patterns of judgment and behavior. In the case of the Normal Vote account, voters are either partisan or not, and these immutable qualities fully control what people do, for example, whether they will pay attention (partisans do, independents do not), when they decide for whom to vote (partisans early in campaigns and nonpartisans late), and so forth.

Partisans have certain qualities and they consistently display them, just as nonpartisans display their characteristic qualities (as we shall see, a similar case can be made for ideology as a stable defining quality). In the case of Rational Choice theory (or its more recent variant, bounded rationality), voters think and act rationally all the time and in every circumstance so long as at least minimal stakes are in play. The orienting insight of Affective Intelligence Theory is that voters shift between different decision strategies, roughly along the lines suggested by the dual process understanding of human judgment.


AIT: voters have different decision patterns. In the familiar condition, it is efficient to swiftly and automatically rely on previous learned rountines. Under unfamiliar condition, people turn to more considerations. 

Familiar and rewarding context -- enthusiasm -- habituated choice

Unfamiliar and uncertain context -- anixety -- deliberative choice

### @LodgeTaber2013 Rationalizing Voter

**Author** Milton Lodge and Charles Taber

**Year** 2013

**Summary**

The John Q. Public Model of automatic beliefs, attitudes, and behaviors. 
Hot cognitiion hypothesis: the claim that with repeated co-activation socio-political concepts become positively or negatively charged and this afftective charge becomes directly linked to the concepts in long-term memory. Thereupon 'feelings' come to mind spontaneouly upon mere activation of the object represented in long-term memory, be it a person, a group, an issue or an event ect.

Emotions come before rational judgements. Motivated reasoning exists. 



## Social Identity Theory



### @Conover1988 The Role of Social Groups in Political Thinking
This article outlines a cognitive-affective model of the role of social groups in political thinking. It assumes that people have stored information and emotional reactions to social groups, and that people are purposive in their thinking about social groups in the sense that they are interested in understanding what various groups have obtained and whether it is deserved. Conovor differentiates two types of in-group attachment: group membership and group identification, and the later part includes both the objective membership and psychological attachment. 
Conover's study is based on the 1984 National Election Study Pilot Study. Questions are constructed around with women's issues. The results show that for ingroups, group identification and consciousness can help structure political thinking so more pro-group actions are taken. In contrast, for out-groups, political sympathy is less likely to occur and people still prefer pro-group issues.

This study touches some important implications in gender, race and parties. Conover only used gender related identities in this study, but nevertheless shows that being male/female changed their views of political empathy. It will be interesting to check if similar effect exists among partisan members. 


### Henry Tajfel 1979 Social Identity Theory

Tajfel (1979) proposed that the groups (e.g. social class, family, football team etc.) which people belonged to were an important source of pride and self-esteem. Groups give us a sense of social identity: a sense of belonging to the social world.

The central hypothesis of social identity theory is that group members of an in-group will seek to find negative aspects of an out-group, thus enhancing their self-image.

Prejudiced views between cultures may result in racism; in its extreme forms, racism may result in genocide, such as occurred in Germany with the Jews, in Rwanda between the Hutus and Tutsis and, more recently, in the former Yugoslavia between the Bosnians and Serbs.

Henri Tajfel proposed that stereotyping (i.e. putting people into groups and categories) is based on a normal cognitive process: the tendency to group things together. In doing so we tend to exaggerate:

1. the differences between groups

2. the similarities of things in the same group.

We categorize people in the same way. We see the group to which we belong (the in-group) as being different from the others (the out-group), and members of the same group as being more similar than they are. Social categorization is one explanation for prejudice attitudes (i.e. them and us mentality) which leads to in-groups and out-groups.


# Women and Politics
## Representation

### Dovi 2011 Political Representation
Dovi provides an overview of the theoretical contributions on representation. She discusses a number of different conceptions of what a representative should be, how they should be held accountable and how we should think about the relationship between representatives and their constituents. She brings up the work of a number of authors who have problematized the principalagent conception of the relationship between representatives and their constituents and also points out that we need to broaden our conception of representation beyond elected officials to include non-governmental organizations. 

Main Findings: 
(a) The author defines political representation as follows: political representation is the activity of making citizens voices, opinions, and perspectives present in the public policy making processes. Political representation occurs when political actors speak, advocate, symbolize, and act on the behalf of others in the political arena. In short, political representation is a kind of political assistance. 

(b) Delegate vs. Trustee representations: Delegate conceptions of representation require representatives to follow their constituents preferences, while trustee conceptions require representatives to follow their own judgment about the proper course of action. Any adequate theory of representation must grapple with these contradictory demands. 

(c) Pitkin (1967) Four views of representation: 
i. Formalistic Representation: The institutional arrangements that precede and initiate representation. Formal representation has two dimensions: authorization and accountability.

ii. Symbolic Representation: The ways that a representative 'stands for' the represented, that is, the meaning that a representative has for those being represented. 

iii. Descriptive Representation: The extent to which a representative resembles those being represented. 

iv. Substantive Representation: The activity of representatives  that is, the actions taken on the behalf of, in the interest of, as an agent of, and as a substitute for the represented. 

(d) Identifies three major problems raised by the literature on representation: i. The first problem is the proper institutional design for representative institutions within democratic polities. ii. ways in which democratic citizens can be marginalized by representative institutions iii. the relationship between representation and democracy


### Beth Reingold and Michele Swers 2011

Viewing Women's interests as endogenous: interets are interesting in and of themselves


### Dovi 2002 

Arguing for descriptive representation criteria:  some descriptive representatives are preferable to others:  P
possess strong mutual relationships with dispossessed subgroup of historically disadvantaged groups.

### Htun 2004 Is Gender Like Ethnicity?
Some 50 countries officially allocate access to political power by gender, ethnicity, or both. Yet in the worlds electoral democracies, the policies used for women differ systematically from those used for ethnic groups. The former receive candidate quotas in parties; the latter, reserved seats in legislatures. Why? My explanation focuses on the varying ways that gender and ethnic identities intersect with partisan cleavages and on the distinct work performed by the different remedies for underrepresentation. Quotas, which make space within existing parties, are appropriate for groups whose boundaries crosscut partisan divisions. Reservations, which create incentives for the formation of group-specific parties and permit them direct representation, suit groups whose boundaries coincide with political cleavages. Since gender is crosscutting while ethnicity tends to be coinciding, women receive candidate quotas while ethnic groups get legislative reservations. Claims for inclusion via quotas pose less of a challenge to liberal institutions than claims to difference through legislative reservations. Case studies of representational politics in France, India, and Peru illustrate the argument.

### Jane Mansbridge 1999 Shouldn Blacks Represent blacks and Women Represent Women? Yes

Disadvantaged groups gain advantages from descriptive representation in at least four contexts. In contexts of group mistrust and uncrystallized interests, the better communication and experiential knowledge of descriptive representatives enhances their substantive representation of the group's interests by improving the quality of deliberation. In contexts of historical political subordination and low de facto legitimacy, descriptive representation helps create a social meaning of "ability to rule" and increases the attachment to the polity of members of the group. When the implementation of descriptive representation involves some costs in other values, paying those costs makes most sense in these specific historical contexts.


### Michele Swers 1998 Are Women More Likely to Vote for Women's Issue Bills?

Women will not necessarily exhibit a more liberal ideology than their male couterparts on all issues, however, the more directly an issue affects women, the more likely it is that women will vote together across party lines.

### Rosabeth Moss Kanter and Drude Dahlerup Critical Mass Theory
(1) with an increase in relative numbers, minority members are potentially allies, can form coalitions, and can affect the culture of the group; (2) with an increase in relative numbers, minority members begin to become individuals differentiated from each other; and (3) despite a lack of change in relative numbers, the presence of feminist or women-identified-women can reduce performance pressures, token isolation and role entrapment if the particular women involved form coalitions.




## Women Participation

### Angela High-pippet and John Comer 1998 Female Enpowerment

The concept of political empowerment has been applied to ethnic and racial minorities, where it has been shown to positively influence political attitudes and participation. We examine whether political empowerment has the same positive consequences for women. Using data from the 1992 National Election Study and Almanac for American Politics 1990, 1992, and 1994, we explore whether women who are represented by women in Congress are more likely to be interested in and participate in politics, have a greater sense of political efficacy, competence, and trust, and evaluate Congress as an institution more favorably than women represented by men. In general, we find women who are represented by women are more interested, participate more, and have greater senses of political efficacy and political competence. Moreover, the findings clearly seem to be a function of empowerment rather than other factors dial might account for both the election of a woman to Congress and differences in attitudes and behavior identified above.

### Amanda Claydon 2015
Lesotho Case

Do affirmative action measures for women in politics change the way constituents view and interact with their female representatives? A subnational randomized policy experiment in Lesotho with single-member districts reserved for female community councilors provides causal evidence to this question. Using survey data, I find that having a quota-mandated female representative either has no effect on or actually reduces several dimensions of womens self-reported engagement with local politics. In addition, implications from the policy experiment suggest that the quota effect is not accounted for by differences in qualifications or competence between the different groups of councilors, but rather stems from citizens negative reactions to the quotas design.

### Amy C. Alexander 2012 Change in Women's Descriptive Representation and the Belief in women's Ability to Govern:  A Virtuous Cycle

### Christina Wolbrecht and David E. Campbell 2007 Leading By Example: Female Memebrs of Parliaments as Political Role Models

One argument advanced in favor of descriptive representation is that female politicians serve as role models, inspiring other women to political activity. While previous research finds female role models affect women's psychological engagement, few studies report an impact on women's active participation, and none have done so in cross-national research. Our work also is the first to consider whether the impact of female role models is, as the term implies, greater among the young. Using three cross-national datasets, we find that where there are more female members of parliament (MPs), adolescent girls are more likely to discuss politics with friends and to intend to participate in politics as adults, and adult women are more likely to discuss and participate in politics. The presence of female MPs registers the same effect on political discussion regardless of age, but the impact on women's political activity is far greater among the young than the old.






## Political Recruitment

### Kate Kenski and Erika Falk 
Of What Is That Glass Ceiling Made?: A Study of Attitudes About Women and the Oval Office

Using data from the 2000 National Annenberg Election Survey, this study examines the predictors of reporting that a woman or man would do a better job as president considering the national issue most important to the respondent. Gender, education, and ideology are strong predictors of presidential gender preference. Naming health care as the most important problem facing the nation is positively associated with believing a female president would do a better job, even when controlling for sociodemographic, party identification, and ideology variables. Selecting taxes as the problem is associated with believing that a male president would do a better job.


### Susan J. Caroll and Krisa Jenkins 2001 Unrealized Opportunity

Term Limits and the Representation of Women in State Legislatures

Using data from the state legislative elections of 1998 and 2000, this article examines empirically the expectation prevalent in the women and politics literature that the implementation of term limits will lead to increases in the numbers of women legislators. At the state house level, in both elections more women were forced to leave state house seats because of term limits than were elected to house seats that were vacated by term-limited incumbents. In contrast, at the state senate level, women increased their numbers in term-limited seats in 1998 and maintained their numbers in 2000. Thus far, women have fared better in term-limited seats for state senates than for state houses because of a pipeline effect whereby some women representatives who have been term-limited out or who face a term-limited future have successfully taken advantage of opportunities to seek senate seats that opened up because of term limits.


### Louise Chappell and Georgina Waylen 2013 Gender and Hidden Life of Institutions

New Institutionalism has shown that the rules of the game are crucial to structuring political life in terms of constraining and enabling political actors and influencing political outcomes. A limitation of this approach, however, has been its overemphasis on formal rules, with much less attention paid to how informal rules work alongside and in conjunction with formal institutions to shape actors and outcomes. This article contributes to an emerging literature that highlights the importance of informal institutions by bringing into focus one element that has been hidden in these debates  the influence of gender norms and practices on the operation and interaction between formal and informal institutions. It highlights some of the key benefits of a gender analysis for understanding political institutions in both their formal and informal guise and considers some of the challenges in building a research agenda that requires new methods and techniques of inquiry.

### Kira Sanbonmatsu 2006 Do Parties Know that "Women Win"? 
Party Leader Beliefs about Women's Electoral Chances

Womens groups emphasize the view that women are viable candidates in American politics with the popular slogan when women run, women win. What do party leaders believe about womens electoral chances? Do parties know that women win? In an analysis of state legislative election results, I find few gender differences in candidates vote share and success ratestwo widely used measures of the status of women candidates. Yet I find that many party leaders report that one gender has an electoral advantage. These party leader perceptions are related to the objective measures of womens electoral success to some extent. However, most analyses reveal a gap between elite perceptions and objective measures of womens status as candidates. This disjuncture suggests that scholars may have overestimated the extent of party leader and voter support for women.


### @FoxLawless2004 Gender and the Decision to Run for Office

**Author** Rihcard Fox and Jennifer Lawless

**Journal** AJPS

**Summary**
A critical void in the research on women's underrepresentation in elective office is an analysis of the initial decision to run for office. Based on data from our Citizen Political Ambition Study, the first large-scale national survey of potential candidates, we examine the process by which women and men emerge as candidates for public office. We find that women who share the same personal characteristics and professional credentials as men express significantly lower levels of political ambition to hold elective office. Two factors explain this gender gap: first, women are far less likely than men to be encouraged to run for office; second, women are significantly less likely than men to view themselves as qualified to run. Our findings call into question the leading theoretical explanations for women's numeric underrepresentation and indicate that, because of vestiges of traditional sex-role socialization, prospects for gender parity in U.S. political institutions are less promising than conventional explanations suggest.

### @Fultonetal2006 Gender and Ambition to Run for Congress

**Author** Sarah A. Fulton and Cherie D. Maestas and L. Sandy Maisel and Walter J. Stone

**Journal** PRQ

**Summary**

Do men and women differ in their decisionmaking calculus for higher office? To answer this question, we use a survey of state legislators (SLs) in 1998 to examine the conditions under which male and female SLs seek a position in the U.S. House of Representatives. We consider three ways in which gender may influence ambition and the decision to runindirectly, directly, and interactivelyand we find evidence of all three effects. Female state legislators are less ambitious than males for a U.S. House seat, a difference that largely stems from gender disparities in child-care responsibilities. However, despite their lower ambition, female SLs are just as likely as their male counterparts to seek a congressional position. This apparent puzzle is solved by the finding that the expected benefit of office mediates the relationship between ambition and the likelihood of running. Female SLs are much more responsive to the expected benefit of office than are males, offsetting their diminished ambition level. The sense of a woman is reflected in female state legislators increased sensitivity to the strategic considerations surrounding a congressional candidacy. Because men and women respond differently to the intersection of ambition and opportunity, gender constitutes an important, yet often neglected, explanatory variable in the decision-to-run calculus.


### Niven 2006 Negative Recruitment and the Gender Imbalance in State Legislative Candidacy

Candidate dropouts are a crucial and understudied population; they represent a significant source for increasing womens candidacies and addressing the gender imbalance in office. Survey evidence demonstrates that women are discouraged from running in districts in which their party is strong, while men are discouraged from running in districts in which their party is weak. Are women more likely to drop out of an election race than are men? If so, why? Using election records and an original survey, this article examines the experiences of all declared candidates for the state legislature in Florida in 2000 and 2002. The sample includes candidates who won office, who lost their races, or who dropped out along the way. Evidence here shows that women are no more likely to drop out of a state legislative race than are men. Among dropouts, however, women are disproportionately likely to drop out from districts in which their party is strong. The results offer support for the contention that political elites continue to value mens political leadership more than womens, and that increasing the number of female officeholders may require efforts to support declared women candidates in the earliest stages of their candidacies.


## Media and Gender Stereotype

### J. H. Black and L. Erikson 2003 Do women politicians need to be better?

Although much contemporary research has found that women candidates do not lose votes, little is known about whether a negative voter bias against women candidates may be disguised or offset by their superior qualifications. Using a unique 1993 Canadian data set that combines aggregate data with survey information from candidates themselves, this paper tested for but did not find such an effect. In fact, the main results indicate that, among similarly situated women and men candidates, women actually had a small vote advantage, even taking into account their higher qualifications. Further analysis aimed at exploring the comparative votegetting ability of women candidates reveals that neither turnout nor urban/rural constituencies appeared to be relevant factors but that office-holding experience in non-political organizations made a modest contribution to womens electoral advantage.

### Leonie Huddy and Nayda Terkildsen 1993 The Consequences of Gender stereotype for women at different levels of office

Despite the recent electoral success of female candiates in local, state, and national elections, we find that voters' gender stereotypes have potentially negative implications for women candidates, especially when running for national office. We test the political impact of stereotypes by examining the relative importance of typical "male" and "female" personality traits and areas of issue competence for "good" politicians and a hypothetical candidate at different types and levels of office. Overall, we find a preference for "male" characteristics at higher levels of office. We attempt to reconcile the existence of gender stereotypes, which portray women candidates as insufficiently aggressive or less competent in their dealings with the military with the recent electoral success of women in national and statewide elections.

### Kim Fridkin 1992 Does Being Male Help: An Investigation of the Effects of Candidate Gender and Campaign Coverage on the Evaluation of U.S. Senate Candidates

This study examines the possibility that the news media, by covering male and female candidates differently, may influence the success of female candidates. A content analysis of newspaper coverage of U.S. Senate campaigns shows that male and female Senate candidates are covered differently in the news. An experiment was conducted to explore the consequences of these differences in coverage, as well as the significance of the candidates' gender, for evaluations of Senate candidates. The experimental results suggest that gender differences in coverage tend to advantage male candidates. For instance, candidates who are covered like male candidates in the news are considered more viable than candidates who are covered like female candidates. Sex stereotypes, on the other hand, can advantage female candidates. Female candidates are viewed as more compassionate and more honest than identical male candidates. The findings from this study support the hypothesis that the mass media may influence a woman's chances of success at the polls. Male and female candidates are covered differently in the news and these differences often produce negative assessments of women candidates.

### Dianne Bystrom and Terry Robertson and Mary Christine Banwart 2001
Framing the Fight

The few research studies that explore the media's portrayal of female candidates in comparison to male candidates have been limited to general election campaigns and usually to one level of office. To expand this area of research, this study examines the media's portrayal of female and male candidates in primary races at two levels of political leadership in which the representation of women is strikingly lowstate governor and U.S. senatorin the 2000 campaign. This study's exploration of how the media portrays female and male candidates relies on a content analysis of articles from major national newspapers and representative major regional newspapers. By studying the media's portrayal of male and female candidates during primary elections at two levels of political leadership, this study provides an understanding about how men and women are framed differently even when vying for their own party's bid and, thus, new insights into how such primary framing can translate into bias during the general elections.

### Elizabeth van Acker 2003 Media Representation of Women Politicians in Australia and New Zealand

Senior women politicians are a novelty, receiving enormous media attention. They have had to deal with high expectations in the media and other political institutions such as Parliament. This essay examines media portrayals of women politicians in Australia and New Zealand. It argues that the media embrace women quickly and fully early in their careers, but attack them very fiercely when things go wrong. The media creates elevated hopes around them when they enter the political arena. Initially, these women can do no wrong as the media raises them on a pedestal. Those who cannot meet the high expectations, however, fall from the pedestal and are often attacked or trivialised. A more recent development, particularly by the Australian media, shapes women into stars, promoting them as personalities. The women themselves may encourage or welcome the celebrity tag. The minute they make mistakes, however, they are judged harshly. I argue that media representations of womens political styles illustrate perceptions about politics that continue to reflect entrenched gender norms. One-dimensional media portrayals do little to challenge these norms. Setting up false distinctions of femininity and masculinity contributes little to pushing womens interests on to the political agenda.





# Personal Thoughts

Bernisky: On Public Opinion

## Unequal Democrcy arguement: 

Bartels 2008: Voters myopic, Rep has better election-year performance (Hibbs 1977 political business cycle)

Achen and Bartels 2016

Martin Gilens 2013

Brady and Verba Voice and Equality 1995

## Congress

Sin 2014: Separation of Power and Legislative Organization
House rule changes is a game between intraparty group, Senate and the president

Justin Grimmer Representation Style 2013

Schickler 2001: Disjointed Pluralism:  Institutional Innovations and the Development of Congress: members have various interests, different interests are salient at different time

David Mayhew 1974 The Electoral Connection: Mayhew presented a purposive theory in which members were assumed to be motivated solely by a desire for reelection. Of little import were the political parties. Their only purpose was to foster the electoral wellbeing of individual representatives, and otherwise leave them free to pursue their own interests. 

Aldrich and Rohde 2000 Conditional Party Government:  The condition in conditional party government concerns the distribution of policy preferences in the two parties. It is increasingly well satisfied the more homogenous the preferences of Members are within each party (especially the majority party), and the more different the preferences are between the two parties Members. The more one party agrees that it wants outcomes that are different from those desired by the opposition, the more the condition is satisfied.

Schiller 1995 Senators as political entrepereneurs: senattor's use of bill sopnsorship is a funtion of institutional and political variables including senority, proximity of reelection, size of state economy, stafff size, committee membership and committee positions

Krehbiel 1990 Congressional Committee Preference Outliers: no significant difference of the policy preferences between the standing committee and the legislature as a whole

Jackson and Kingdon 1992 Ideology, Interest Group Scores and Legislative Votes: ADA (American Democratic Action) score is measured by roll-call votes, can't be used as an IV to explain vote choices. 


## Party in Congress
Krehbiel 1993 Where's the party: party votes defined as vote according to partisanship despite personal disagreement. no significant evidence

Krehbiel 1999 Paradoxes of Parties in Congress: measurements of the vote-based partisanship is inherently flawed, cannot detect the true partisan effect

Krehbiel 1995 Cosponsors and wafflers from a to Z: bill sponsorship is preference-bases. Wallfing: defined as bill cosponsorhsip but refusal to sign a discharge pentition for the bill, should be negatively related to prference extremity and unaffected by the party membership.

Binder Lawrence and Maltzman 1999 Uncovering the Hidden Effect of Party: Reexamning the 1994 'A to Z' petition, separating individual's policy preference with partisan labels, they found clear partisan divergence

Hager and Talbert 2000 using roll-call data from 1950s to 1990s, regression analysis show the effect of party voting. Switchers change votes after switching

Cooper and Brady 1981 Leadership style in congress: when party strength is high, more hierarchial style, when weak more bargaining style. 

Snyder and Groseclose 2000: differentiating procedural and substantive roll-call votes, partisan effect important on procedural votes, as well as economic and security -related substansive topics.

Cox and McCubbins 1994 the Stability of Parties in the House: party members are bonded by extra-legislative organization and bond posting. Caucus members must obey caucus rules, violations will cause expulsion. 

Patterson and Caldeira 1988 Party Voting in the Congress: Party voting less in Senate due to the more stable term limits: a considerable lag. 

## Agenda Setting

Cox and McCubbins 1993 Legislative Leviathan: Majority party cartels sets the agenda rules. 

McCubbins and Schwartz 1984 Congressional Oversight Overlooked, Police Patrols versus Fire Alarms Police patrol oversight,  is the routine work of "patrolling" the executive branch looking for problems in program implementation. It is usually centralized in a legislature in an audit or program review committee with a staff agency that evaluates the performance of executive agencies. It relies on formal committee hearings on agency operations and on interim studies and reports on legislative performance. Police patrol oversight is usually initiated by the legislature and tends to be formal and systematic.
Fire alarm oversight of executive programs by legislatures occurs when interest groups complain about how programs are administered, the media expose programmatic waste or abuse, or constituents report problems with government services that reveal flaws in program design or implementation. It is highly decentralized, relies on outside actors to "sound an alarm", and is less than systematic.
Congress put more attention to fire alarm oversight, in part because it provides media attention and credit-taking opportunities, and that it is an equally effective way of correcting problems with government programs.

## Partisanship and Ideology

Hans Noel 2013 Political Ideology and Political Parties: ideologues are different from partisans, political intellucts precedes partisans

Conover and Feldman 1981 The Origins and Meaning of Liberal/Conservative Self-Identifications. affective evaluation, ideology is not unidimensional

Desmarais et al. 2015 Extended Party Network: parties backed by interest groups

John Aldrich 1995 Why Parties: parties are endogenous insitituions for election

Bawn et al. 2012 A Theory of Political Parties: parties driven by policy demanders 

Hans Noel 2013 Political Ideology and Political Parties

Lane 1962 Political Ideology most American's view of the events of everyday life are morselized, they are not seen as a connected pattern. Ideologues takes his cue on the interpretation of information from all sources 

Lavine, Johnson and Steenbergen 2015 The Ambivalent Partisanship: happens when there's disconnection between long-term party id and short-term party evaluation. 

Fiorina 1981 Exploration of a political theory of party identification: party id is a running tally of retrospective evaluations

Bartels 2002 Beyond the Running Tally

Green et al. 2002 Partisan Hearts and Minds: early childhood, persist

Abramowitz and Saunders 2006 Exploring the Bases of Partisanship: Party is related to ideological preferences, rather than social group membership.  


## Polarization
Burden, Jones and Kang 2014 Sore Loser Laws and Congressional Polarization: Sore lose laws increase polarization

Druckman, Peterson and Slothuus 2013 Elite Polarization and Public Opinion Formation: polarization affect how citizens think, intensifies the impact of party endorsements, decreases the impact of substansive information and stimulates greater confidence in those-- less substansively grounded opinions. 




## Public Opinion
Converse 1964 The Nature of Belief System of the Mass Public

Achen 1975 Converse's result of low constrait is due to the variation of survey questions, measurement error

Zaller and Feldman 1981 A Simple Theory of Survey Response: Survey Responses may not refelct the true preferences:
ambivalence, response, and accessibility

Zaller 1992 The Nature and Origins of Mass Opinion: The RAS (Receive-Accept-Sample) model: when asked, people will sample a mix of positive/negative feelings from the top of the mind. The effect of campaign depends on the relative intensity of the opposing messages individual's prior stores of partisan information. 

Goren 2001 Core Principles and Policy Reasoning: people do refer to core values like individualism and equal pooprtunity, but core principles influence policy preferences more with more expertised people. 

Goren 2004 Political Sophistication and Policy Reasoning: unlike Zaller, political sophistification do not condition the usage of abstract value principles. 

Gerber et al. 2010 Personality and Political Attitudes: Big Five Traits affect economic and social attitudes differently, and vary substantially between white and black respondents. 
Openness to experience; conscientiousness, extraversion, agreeableness, neuroticism

Feldman 1988 Structure and Consistency in Public Opinion: the Role of Core Beliefs and Values: political preferences are structured by core beliefs and values.

## Opinion and Public Policy

Green and Gerken 1998 Self-Interest and Public Opinion toward Smoking Restrictions

Citrin et al 1997 Public Opinion Toward Immigration Reform: 1992 and 1994 NES Personal Conditions not matter, beliefs about national conditions, attitudes towards Asians and Latinos matter 

Funk 2000 The Dual Influence of Self-Interest and Societal Interest in Public Opinion-- citizens use both, but sometimes willing to sacrifice, topic: socil welfare

Sears et al. 1980 Self-Interest vs. symbolic Attitudes and Presidential Voting -- self-interest plays little role, ideology matters 

Alvarez and Brehm 1995 American Ambivalence towards abortion policy: conflicting beliefs leads to ambivalence about policy choices

Jacoby 2006 Value Choices and American Public Opinion: there exists a hierachical structure of the value system

Hurwitz and Peffley 1987 A Hierarchical Model of Foreign Policy Attitude -- similar to previous article 

## Rational Public

Kuklinski and Quirk 2000 Reconsidering the Rational public: heuristics are not that great

Daniel Shacter 1999 Seven Sins of Memory

Wilson and schooler 1991 Thinking too Much: overthinking reduces decision quality

Page and Shapiro 1992 the Rational Public: collective rationality

## Theories of Political Psychology

Elaboration Likelihood Model Petty and Caciopo

Heuristic-Systematic Model Shelly Chaiken

John Q. Public: Lodge et al. 2013

Motivated Reasoning (Redlawsk 2002): Affective Bias takes longer time for citizens to process information incongruent with existing affect

MODE model (motivation and opportunity as determinants of the attitude-behavior relation) Fazio and Towles-Schwen
when both are present, behavior will be deliberate, when one is absent, impact on behavior will be spontaneous. 

Theory of Affective Intelligence; Mackuen et al. 2007 condition on familiar/unfamilar issues: familiar and rewarding context -- enthusiasm -- habituated choice; unfamiliar and unceretain context -- anxiety -- deliberative choice

Social Identity Theory: Tajfel 1979 favor in-group, depreciate out-group


## Campaign 

Druckman, Kifer and Parkin 2009: Challengers use more negative ADs, emphasize on issues and personality; incumbents emphasize on experience

Chong and Druckman 2010 Dynamic Public Opinion: Competing information during the campaign will cancell each other; meanwhile individuals will give disportionate weights to the most recent info. 

Kalr 2013 The Influence of Competing Identity Primes on Poitical Preferences: people have different identities, threateing is more effective 

Bartels 1993 Messages Received: Adjusting for measurement error, media does have more than minimal effect on presidential election, Bayesian method, mostly effective on weak opinioners

Ansolabehere et al. (AISV) 1994 Does Attack AD Demobilize the Electorate: Yes drop intentions by 5% 1992 CA state Senate Race

Finkel and Geer 1998 A Spot Check: presidential campaign, TS analysis, no negative effect 

Kahn and Kenny 1999 Clarifying the Relationship Between Negativity and Participation 1990NES, people distinguish between useful info and mudslinging

Kahn and Kenny 2002 the Slant of News Editorail Endorsement Influence Campaign Coverage and Citizens' Views of Candidates 

Lau et al. 1999 Meta Analysis of Negative ADs on Tunrout: no support


## Media

Iyengar and Kinder 1987 News that Matters: Media can change public opinion through priming, framing and agenda setting

Kinder and Sanders 1990 Mimichking Political Debate with Survey Questions, the Case of White Opinion on Affirmative Action for Blacks: framing through unfair advantage or reversed discrimation produced different opinions

Page, Shapiro and Dempesey 1987 what moves public opinions: news media parallel opinion changes.

Mutz 1994 Contextualing Personal Experice: the role of mass media: exposing people to similar experiences of others 

Hopkins 2012 Local oppositions to Immigrants: the saliency of news media moderates the hostile attitudes toward immigrants.

Egan and Mullin 2012 Turning Personal Experience into Political Attitude: the Effect of Local Weather on perceptions about global warming


## Voting

Brady and Verba 1995 resource model: thet can't that don't want to, no body asked 

Brady and Verba 1995 Voice and Equality

Downs 1957 Economic Theory of Democracy

Campbell et al. 1960 American Voter: partisan votes, issue not matter 

Lewis-Beck et al. 2008 The American Voter Revisited: no changes

Achen and Bartels 2016 Democracy for Realists : partisan voting, voters don't vote on issues

Lewis-Beck and Stegmaier 2007 Economic Voting

Kelley and Mirer 1974 Simple Act of Voting: averaging the likes and dislikes of the leading candidates and parites

Jessee 2009 Spatial Voting in the 2004 Presidential Election: happens among individuals, but partisans have biased spatial voting 

Tomz and Van Houweling 2008: check proximity theory, discounting theory and directional theory -- turns out proximity theory works at the best 

Tomz and Van Houweling 2009 The Electoral Implications of Candidate Ambiguity: in nonpartisan and partisan settings, voters have no negative preference over candidate taking ambiguious positions. 

Kinder and Kiewiet 1979 Economic Discontent and Political Behavior: The Role of Personal Grievance in Economic Judgments in Congressional Voting -- not pocket-book voting, more a socio-tropic voting 

Lupia 1994 Shortcuts versus encyclopedias: information and voting behavior in California insurance reform elections

## Evaluation

Brandon, Cassese and Jones (2012): House incumbent evaluation: no evidence of race-based on Afro, Latinos and Whites are

Lodge, Steenbergen and Brau 1995 Responsive Voter: online model of candidate evaluation 

Dancey and Sheagley (2013) raise the issue that one should be cautious about the utility of party cues and heuristic decisions. They find that putting party cues in mind, even highly informed voters tend to overestimate the consistence between their positions and senators positions. In other words, heuristic use of party cues lead these highly knowledgeable voters to be misinformed about policy positions.

Forgette and Morris (2006) for instance use an experimental design to examine how CNNs Crossfire and Inside Politics coverage and analyses of the State of Union Address influenced viewers political attitudes. Their results show that high-conflict media exposure decreases viewers evaluations of political institutions, trust in leaderships and overall support of political system. 

A study done by Miller and Krosnick (2000) shows that trust in news media plays a pivotal role in conditioning the effect of media exposure. They find out that politically sophisticated individuals who trust the media coverage that issues discussed in the media is important, leading these people to pay more attention to the mentioned issues when evaluating politicians.

## Representation

Hanna Pitkin 1967 The Concept of Representation

Bafumi and Herron 2010 Leapfrog Representation: when a congressional legislator is replaced by a new member from the opposite party, one relative extremist is replaced by another extremist. Senate is more stable. 


## Gender

Brooks 2013 He Runs She Runs: No significant evidence of gender stereotype

Dovi 2002 criteria for descriptive representation: strong mutual relationship with dispossessed subgroup of hostirically disadvantaged groups.

Mansbridge 1999 should Blacks Representa Blacks and Women Represent Women: mutual trust, better communication and knowledge, ability to rule

Swers 1998 Are Women More likely to vote for women's issue bills? Yes, on family children etc

High-pippet and Comer 1998 Female Enpowerment: Yes

Alexander 2012 Change in Women's Descriptive Representation and the Belief in women's ability to govern: a virtunous cirtle

Fridkin 1992 Does Being Male Help: YES

## Racial Threat Hypothesis

Situated within the conflict perspective, the racial threat hypothesis argues that members of the majority groupin this case, whitesperceive the relative size of and increases in the black population as threatening and in turn take actions to reduce this perceived threat. 

Blalock 1967 Economic Threat and Political Threat

Kinder and Kam 2010 US Against Them: Ethnocentric Foundations of American Opinion

Parker and Barreto 2013 Change They Can't Believe In: The Tea Party and Reactionary Politics in America
Tea party as identity politics, Obama as a symbolic threat
