---
output: 
  bookdown::pdf_document2:
    toc: true
    citation_package: natbib
    keep_tex: false
    fig_caption: true
    latex_engine: pdflatex
title: "American Comprehensive Exam Notes"
author: 
- Hao Wang
- Arizona State University
date: '`r format(Sys.Date(), "%B %d, %Y")`'
geometry: margin=1in
fontfamily: mathpazo
fontsize: 12pt
spacing: single
papersize: letter
bibliography: ~/Dropbox/bib/Haowang.bib
biblio-style: apsr
citecolor: blue
header-includes: \usepackage{graphicx, longtable, float, subfigure}
---


\newpage

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```





# On Method Questions

## @BradyCollier2010 Rethinking Social Inquiry

**Author** Henry Brady and David Collier

**Year** 2010

The difference between experiments and observational studies. 
KKV: use statistical (regression) ideas and principles into political analysis. Three criteria: unbiaseness, efficiency and consistency. Unbiased estimates that those that are replicated as the average when the same methods of inference are applied again and again to an event. If a measure shifts in the estimate in one way or the other, it is called bias. One major source of bias is that the informants who answer poll questions over under- or over-state their estimates to questions(p. 64). Efficiency, on the other hand, is a relative concept measured by calculating the variance of the estimator across hypothetical replications; the more observations there are, the better (i.e. smaller)
the variability.

Conditional independence and specification assumption. The former one is the model of a statistical control. The later one is based on statistical models and restrictions. 

Different from KKV: always increasing N is not a good idea. The later cases may be unrelevant to causal inference. Instead they argue for adding causal-process observations. (p.195)


## @Mahoney2010 After KKV

**Author** James Mahoney

**Year** 2010

**Summary**

KKV's approach: process tracing as the search for intervening variables is useless. Their suggestion is to expand the size of N to achieve a determinate research design. 

Brady and Collier: data-set observtion and causal-process observation. 

Mahoney's approach: theory-testing usage of causal-process observation: independent variable CPOs, mechanism CPOs, and Auxiliary CPOs. Independent CPOs: provides information about the presence of an independent variable. Mechanism CPOs provides information about whether an intervening event posited by a theory is present. Auxiliary outcoe CPOs: information about particular occurences that should occur alongside the main outcome interest if in fact that outcome were caused in the way stipulated by the theory under investigation. Auxiliary outcomes are separate occurences that should be generated if the theory works. 

## @Lijphart1971 Comparative Politics and Comparative Method

**Author** Lijphart

**Year** 1971

**Summary** 
Comparative method as one methoe comparing to experimental, ans statistical method. Comparative method resembles statistical method, but the number of cases are much smaller. 

Four suggestions:
1. Increase the number of cases as much as possible. 2. Reduce the 'property-space' analysis: if the sample of cases cannot be increased, it may be possible to combine two or more variables that express an essentially similar underlying characteristic into a single variable. 3. Focus the comparative analysis on comparable cases. 4. Focus on key variables. 

## @Mahoney2008 Toward a Unified Theory of Causality

**Author** James Mahoney

**Year** 2008

**Journal** CPS

**Summary**
Case-oriented approach and population-oriented approach. Case-oriented research focuses on the necessary and sufficient conditions of causal mechanism. The population-oriented approach focuses on the typical effect, e.g. does development causes democracy? Suffcient and necessary causes. Population research with insufficient and necessary items. 

## James Mahoney and Dietrich Rueschemeyer 2003 in (Comparative Historical Analysis)

Achievements and agendas

Definitions of CHA: 1. concerned with explanation and causal identification 2. explicitly analyze historical sequences and take seriously the unfolding process over time. 3. engage in systematic and contextualizex comparisons of similar and contrasting cases. 

## Snyder 2001 Scalding Down



## James Mahoney Strategies of Causal Assessment in CHA 2003

Three basic causal assessment strategies: nominal, ordinal and within-case strategies. In the with-case stage: pattern matching, process-tracing and causal narrative. 


# Power and State

## @Huntington2008 Political Order in Changing Society

**Author** Samuel Huntington

**Year** 1968

**Summary**
Development causes political instability. Institutions that are more adaptable can withhold the instability brought by the social and economic development. Social developmeny increases political participation, and thereby instable factors. 

## @Spruyt1994 State Anarchy as Order

**Author** Hendrik Spruyt

**Year** 1994

**Journal** IO

**Summary** 
Why soveign territories displaced other rivalry format? Sovereign territorial state prevailed because it proved more effective at preventing defection by its members, reducing internal transaction costs, and making credible commitments to other units. It did this is three ways, first sovereign rulers were better at centralizing jurisdiction and authority. Consequently better at preventing free-riders. Second, sovereign territory was a means of structuring interunit behavior. States, or rather political social elites within that territory preferred similar styles. Third, due to the first two conditions, actors from other institutional arrangements defected to states or copied their institutional makeup. 

## @Levi1981 The Predatory Theory of Rule

**Author** Margaret Levi

**Year** 1981

**Summary**
Trying to explain state behaviors. Why state pick some actions rather than others? State as a ruller. State as the ruler is predatory in that he attempts to formulate policies that maximize his personal objectives but that his success is dependent on his bargaining power vis-a-vis subjects, agents, and external actors. Policies are outcomes between rulers and individuals/groups. 

Rulers take control over the state by force and control. The predatory theory argues that rulers will seek to design policies that miximize his revenues and power. However, because his ends often conflict with those of other, his policies are generally the outcome of a trade. The variations in policies are function of the constraints on the ruler's bargaining power in relation to specific groups of subjects, agents, external actors. **a ration comparison between rulers and agents**




## @Warner2001 The rise of the state system in Africa

**Author** Carolyn Warner

**Year** 2001

**Summary**
Concept of a state : Most definitions convey the notion that the state is an entity which controls conflict between individuals within a bounded territory, or, conversely, calls upon individuals to participate in conflicts with other bounded territories. Another view is that the state is the allocative mechanism within a political system.4 Such a system is one in which humans continuously interact with one another as they seek to satisfy their individual desires. In a political system, there is some general agreement on the 'rules of the game', and support for the government in its role as the mediator of competing claims. A third view is of the state as a symbolic system, in which ritual and culture create and bind a political community.

The realist approach: (Karl Schmitt): athoritive allocator. State as 'organized violence'

The IR approach, state with three distinct features: 1. hierarchial authority structure which accepts no external territorial jurisdiction, that is, it has sovereign authority 2. territorial demarcation with formal boundaries 3. a public judicial authority with codified laws. 


## @AcemogluRobinson2006 Economic Backwardness in Political Perspective

**Author** Acemoglu and Robinson

**Year** 2006

**Journal** APSR

**Summary**

Political replacement effect: under certain conditions elites will block the development and introduce of new technology. Innovations often erode elites' incumbency advantage, increasing the likelihood that they will be replaced. Fearing replacement, political elites are unwilling to initiate change and may even block economic development. Elites are unlikely to block development when there is a high degree of political competition or when they are highly entrenched. It is only when political competition is limited and also when their power is threatened that elites will block development. Blocking is also more likely when political stakes are higher, for example, because of land rents enjoyed by the elites. External threats, on the other hand, may reduce incentives to block. 

No-blcoking case: UK and Germany, Japan
Blcoking case: Habsburg Empire, Russia

Collorary: Gerschenkron (1962) Economci Backwardness in Historical Perspective, how backward economices lacking the economic prerequsites for inductralization could compensate in different ways. 

## @BlaydesChaney2013 The Feudal Revolution and Europe's Rise: Political Divergence of the Christian West and the Muslim World Before 1500 CE

**Author** Lisa Blaydes and Eirc Chaney

**Year** 2013

**Journal** APSR

**Summary**
We document a divergence in the duration of rule for monarchs in Western Europe and the Islamic world beginning in the medieval period. While leadership tenures in the two regions were similar in the 8th century, Christian kings became increasingly long lived compared to Muslim sultans. We argue that forms of executive constraint that emerged under feudal institutions in Western Europe were associated with increased political stability and find empirical support for this argument. While feudal institutions served as the basis for military recruitment by European monarchs, Muslim sultans relied on mamlukism-or the use of military slaves imported from non-Muslim lands. Dependence on mamluk armies limited the bargaining strength of local notables vis-a-vis the sultan, hindering the development of a productively adversarial relationship between ruler and local elites. We argue that Muslim societies' reliance on mamluks, rather than local elites, as the basis for military
leadership, may explain why the Glorious Revolution occurred in England, not Egypt.

Decentralizing power increases the cost of an unsuccessful revolt for the monarch's rivals. In other words, armed local elites in Europe were able to extract a better 'soft contract' from their monarch than in the Islamic world and were, therefore, less likely to overthrow that monarch. 

# Lipset Przeworski and Limongi Boix and Stokes

## @Lipset1959 Some social requsites of democracy

## @Przeworski1997 Modernization, Theories and Facts 

## @BoixStokes2003 Endogenous Democratization


The relationship between economic growth and democracy is perhaps the most studied topic of comparative politics. Since Lipset (1959), a number of political scientists have engaged themselves in evaluating the impact of economic development on democracy-oriented political transitions as well as on the endurance of existing democracies. In other words, scholars pay attention, to use the metaphoric terminology, to the role economic development plays in the birth, survival, death, and sometimes, rebirth, of democracy.

They do not agree with each other, to some extent, on basic facts and explanations. Lipset insists that economic development, among other things, is one of the social requisites of democracy. Przeworski and Limongi (1997) argue that economic development influences democratic survival more than it influences transitions from dictatorship to democracy, while Boix and Stokes (2003) challenge their theory and reexamine the role of economic development in achieving and sustaining democracy based on a larger dataset with a more sophisticated statistical assessment.

Specifically, Lipset's study (1959) makes the classic statement on the relationship between modernization and democracy. He first establishes the link between per capita income and democracy based on cross-national and cross-sectional data. The rise in per capita GDP, Lipset argues, generates a transition to democracy. If a country develops over a longer period under dictatorship,the cumulated modernizing consequences will embrace democracy (see Przeworski and Limongi, 1997, p. 160). This modernization model, or endogenous explanation, in the terms of Przeworski and Limongi, hypothesizes a close association between development and democracy. For more than four decades, it has been the theoretical basis for empirical studies of the issue in the direction of comparative politics.

While previous quantitative studies go for the standard modernization line, Przeworski and Limongi (1997) provide alternative views on the development and democracy relationship in terms of endogenous vs. exogenous theory. They point out that economic development cannot explain transitions to democracy from 1950 to 1990. Transitions to democracy can take place at any level of economic development due to exogenous causes. Przeworski and Limongi assert that the correlation between economic growth and democratization does not necessarily entail causation, that is, modernization, especially the increase in per capita GDP, is not a causal factor in the process of democratization. There are no grounds to believe that economic development breeds democracies (p.167). Rather, their probit models show that democracy becomes more durable at higher levels of per capita income. They insist, therefore, that it is not that democracies are more likely to emerge when countries develop under authoritarianism, but that, however they do emerge, they are more likely to survive in countries that are already developed (P. 167). In other words, the fact that rich democracies tend not to collapse explains why there is a positive relationship between economic development and democracy. Meanwhile, economic development improves the probability for the sustentation of democracy far more than it improves the odds for a transition to democracy.

Nevertheless, Przeworski and Limongi's judgment that economic development does not play a significant role in transitions away from autocracy has been found flawed by Boix and Stokes reassessment (2003). Boix and Stokes contend that economic development does substantially increase the probability that a country will undertake a transition to democracy, which is labeled as endogenous democratization by Przeworski and Limongi. Yet they admit that development has a much greater positive effect on the probability of maintaining a democracy.

Although the above studies indeed present substantial evidence to illustrate a strong, positive relationship between economic development and democracy despite the differences in approach, they obviously leave many questions unanswered.

First, the tentative conclusions of these scholars have not yet revealed causal mechanisms linking development to democracy. For instance, Lipset early study focuses on their correlation, but examines neither the impact of GDP on democratization nor its ability to promote the consolidation of established democracies. Albeit Przeworski and Limongi have touched upon the fundamental question, they fail to articulate certain mechanisms to explain the influence of development not on transitions, but on democratic survival.

Second, the question of why democracy and wealth are associated with each other remains unexplained at micro, or to be more accurate, individual level. Do the poor care less about democracy? Do richer individuals have greater concern for democracy? In Lipset notion, when a society is more developed, people tend to care more about democracy and support it more. Is that true? Przeworski and Limongi also imply that even the poor in a rich democracy prefer their current regime to a regression to a dictatorship, whereas democracy-minded people under a dictatorship, no matter poor or rich, tend to increase as per capita income of the country raises. Unfortunately, they fall short of collecting empirical evidence at the individual level.

Third, when considering the democracy and development relationship, in which democracy is evaluated as a dependent variable and economic development an independent variable, we should  not ignore another body of literature, which discusses the democracy and poverty relationship. Some scholars argue that poor people have benefited from living under democratic governments; others suggest that democracies have not functioned well for their poorest citizens. Democracy is examined here as an independent variable. Does democracy help create social wealth and better living standard for human beings, or, reversely, is it true that only an affluent society makes the ideal of democratization come true (also see Dahl's discussion on the causal direction, 1971, p. 70)?  Causal directions still is remained as a chicken vs. egg puzzle (which comes first?).

Fourth, the wisdom received for development and democracy relationship, whether proposed by the modernization model or endogenous vs. exogenous theory, notwithstanding, should be tested to see its long-term robustness. Lipset expects their positive correlation has a long-term stability, but it is reasonable to assume that this association may vary over time. Given that his studies come out too early to include post-Cold war data since 1990, his forecast needs more empirical evidence to support. The same situation applies to Przeworski and Limongi, and Boix and Stokes. As we know, during the past 15 years many countries, the former Soviet Bloc countries in particular, had made a transition to democracy. Classic hypotheses regarding the association between democracy and development should be further testified with more extensive data.

Moreover, methodologically, we must bear in mind that different measurement and different datasets could lead to divergent results. The following points, among others, are worthy of further discussion.

(1) The measurement of democracy. Lipset defines democracy as a political system which supplies regular constitutional opportunities for changing the governing officials (p. 71). He does not give his operational definition explicitly, although he indicates stable vs. unstable dichotomy in his data analysis. Przeworski and Limongi give a similar definition (p. 178), and treat democracy as a categorical variable by classifying 224 regimes into two groups: democracy and dictatorship. Biox and Stokes, due to their partial replication of Przeworski and Limongi's study, do not introduce a theoretical or operational concept of democracy of their own. We wonder whether the way they use in classification of democracy vs. dictatorship could be a cause of the divergence in their analyses. 

(2) The indicators of economic development. Przeworski and Limongi (1997) apply a narrow measurement by using GNP per capita, in order to limit their discussion in an elementary descriptive pattern (p. 156). This indicator is obviously over-reductive. Lipset applies a more extensive measurement, which contains four indices including industrialization, wealth, urbanization and education. This composite index can still be expanded. However, Lipset does not report the inter-item reliability. Can these indices for measuring economic development reliable? Earning $ 40,000 a year has different implications for an American family today from 20 years ago. By the same token, owning a car is a label of wealth in China though it is not so in the US. We need to be very careful when selecting indicators to measure economic development. More refined and reliable measurement of regime types, as well as development levels, is required for future studies.

(3) The datasets. The different conclusions on the relationship between development and democracy in these studies may result from the different sample of country or countries. We notice that Lipset studies European and Latin American countries, whereas Przeworski and Limongi include 135 countries all over the world in their study. On the other hand, Boix and Stokes incorporate data beginning from 1850. The comprehensiveness of their dataset helps them challenge the assertion of Przeworski and Limongi. If scholars take a look at the data of the last 15 years, would the conclusions be the same?

(4) Extra variables and certain contexts. No matter we examine the development and democracy relationship as a liner or non-liner causal model, we can neither omit some variable that influence development levels in priori, nor overlook their interactions, before evaluating the independent effect of development on democracy. Besides, studies may vary considerably in the incorporation of other possible control variables in the analyses, such as international relations, geographical factors, to name a few. Moreover, when dealing with large-N cases as a general phenomenon, we need to investigate how various contexts amplify or diminish the effect of development expected from the general theoretical hypotheses of democracy. In other words, when we explore some law-like generalizations, we must critically inquire about the necessity and means of modifying those generalizations under certain circumstances.

(5) Statistical testing. While acknowledging their theoretical contributions, we should note the limitation in Przeworski and Limongi's interpretation of their data analysis. Their probit model, employed also by Biox and Stokes, is undoubtedly more sophisticated than Lipset's cross-tabulations. Unfortunately, however, they do not bother to report the statistical significance between frequencies, as well as between probit values, hence the vulnerability of their models. 

# State Building

## @Ertman1997 Birth of Leviathan

**Author** Thomas Ertman

**Year** 1997

**Summary**
The most valuable contribution Ertman makes to the literature is in his substantial challenge to previously accepted models of early modern political development which link absolutist 'regimes' with bureaucratic apparatuses and constitutional regimes with its absence. His cases reveal that four distinct combinations were developed in Europe in this period: patrimonial absolutism, bureaucratic absolutism, patrimonial constitutionalism, and bureaucratic constitutionalism in Latin Europe, major German States and Denmark, Poland and Hungary, and Britain and Sweden respectively.  These distinctions matter not only in terms of providing more accurate typologies by which to categorize states but because they highlight the crucial impact of particular historical conditions which lead to their emergence.  In his estimation three variables matter in determining these outcomes: the character of local governance in the first centuries after state formation, the timing of the onset of sustained geopolitical competition, and the independent influence of strong representative assemblies on administrative institutions (Ertman 1997, 6).



## @Evansetal1985 Bringing State Back in

### Theda Skocpol Bringing state back

**Summary**
The autonomy of a state: states conceived as organizations claiming control over territories and people may formulate and pursue goals that are not simply reflective of the demands or interests of social groups, classes, or society. 

Bringing state back in the political analysis: state as organizations through which official collectivities may prusue distinctive goals realizing them more ot less effectively given the available state resources in relation to social settings. On the other hand, states may be viewed more macro-scopically as configurations of organization and action that influcen the meanings and methods of politics for all groups and classes in society.

chapter 1, 5, 6, 11.

### Charles Tilly War Making and State Making as Organized Crime
Tilly argues that "war makes states". Historically, competition among "wielders of coercion" for control over territory and resources led to the characteristic European-style state familiar to us today, complete with a military, police force, tax bureaucracy, and courts of law.
a) Successful war making (defeating external enemies) also helped rulers use force to disarm domestic rivals (like lords with private armies, or in a more contemporary sense: warlords, leaders of local militias). It allowed the concentration of coercive power in the hands of the ruler. (state making)
b) War making spurred the development of state apparatuses, such as tax bureaucracies to extract taxes from society to finance the war effort. (extraction)
c) To facilitate further success in war making, states promoted capital accumulation to ensure adequate resources would be available to the state. Courts of law provided one way to protect the property claims of powerful subjects/citizens without allowing those subjects/citizens to use force directly to defend their property. (protection) 

War making promotes state building: to make effective war, they attempted to locate more capita. In the short run, the quest inevitably involved them inestablishing regular access to capitalists who could supply and arrange credit and in imposing one form of regular taxation or another on the people and activitiest within their sphere of control. As the process continued, state makers developed a durable interest in promoting the accumation of capital, sometimes in the guise of direct return to their own enterprise. Variations in the difficulty of collecting taxes, in the expense of the particular kind of armed force adopted, in the amount of war making required to hold off competitors, and so on resulted in the principal variations in the forms of European states. It all began with the effort to monopolize the means of violence within a delimited territory adjacent to a power holder's base. 

What state does: 1. war making: eliminating or neutralizing their won rivals outsiede the territories in which they have clear and continuous priority as wielders of force 2. state making: elimating or neutralizing their rivals inside those territories  3. protection: eliminating or neutralizing the enemies of their clients 4. extration: acquiring the means of carrying out the first three activities -- war making. state making and protection. 

### Peter Evans transnational linkages and the economic role of the state
How does transnational market affect the role of the state?

Evans' hypothesis in this chapter: an intensification of transnational economic linkages tends to be associated with an expansion of the state's role in a range of developing countries, and that such intensification has a dampening effect on the exapnsion of the state's role in those core countries that become major capital exporters.

"That state apparatuses in Third World countries are constrained by transnational linkages in ways that undermine their ability to promote domestic accumulation is incontrovertible. Nonetheless, the challenges of dealing with transnational linkages in general and contests with transnational capital in particular may, under certain circumstances, stimulate the development of new state capacities and may legitimate the expansion of the state's role into areas that would otherwise be the preserve of private capital."

In advanced countries, TNC (transnational companies) may inhibit the expansion of the state's role (case: US, UK).  

### Peter Evans Dietrich Rueschemeyer and Theda Skocpol On the Road toward a More Adequate Understanding of the State

Studying States through analytical induction and historically comparisons: draws from the previous theories and research questions, then explore ideas through comparative and historical research. 



## @KingLieberman2009 A Comparative Perspective on the American State Building

**Author** Desmond King and Robert Lieberman

**Journal** WP

**Year** 2009

**Summary**
This is a book review of 4.

Daniel Ziblatt 2006: Structureing the State: The Formation of Italy and Germany and the Puzzle of Federalism
Federalism is the consequence of an incomplete state-building process that ffectively dissipates and inhibits the further development of centralized state capacity: infrastructural power refers to the state's capacity to penetrate society and implement deceisions through the coordinated activity of civil-society actors, as distinguished from despotic power, which describes the state's abiliy to coerce compliance. The relative infrastructural power of the subnational units determines the future of a federal system or not. (Germany and Italy)

Anna Grzymala-Busse 2007 Rebuilding Leviathan: Party Competition and State Exploitation in Post-Communisit Democracies 
Strong political parties are conducive to state building: cases from the post-communist countries, those with strong political competitions procuded greater constraints on incumbents' capacity to exploit the state and, consequently on the development of the state's own coercive capacity.

Kimberley S. Johnson 2007 Governing the American State: Congress and the New Federalism 2007
how did the Gilded Age and the Progessive Era referomers overcome the barriers imposed by the strcuture of the 19th Century American state? 
intergoverntal policy making of the state government -- the coercive capacity rested with local government 

Jacob S. Hacker 2002 The Divided Welfare State: the Battle over public and private social benefits in the United States.

Due to the tranditional weak states, private sectors like the insurance companies enter into the the tranditionally-conisidered 'state' domain





## @Krasner1984 Approaches to the State: Alternative conceptions and historical dynamics

**Author** Stephen Krasner

**Year** 1984

**Summary**

The statist approach: 1. see politics as a problem of rule and control rather than as one of allocation. 2. Treat state as an independent actor, cam either be exogenous or endogenous. 3. emphasize on institutional constriants. 4. more axious to take the 'historical cue'. 5. statist arguments are more inclined to see disjunctures and stress within any given political systems. 

Comparing with the pluralist approach: Dahl (who governs): pluralism emphasizes the problem of allocation rather than ones of rule and control. Dahl views the state as a collection of individuals occupying particular roles, not as an administrative apparatus or legal order. 


## Dan Slater 2008 Can Leviathan be Democratic?

Competitive Elections, Robust Mass Politics, and State Infrastructural Power

Effective government and accountable government 

Elections are helpful in buidling state capacities: 1. the contructions of mass political parties 2. vote registration of marginalized popultions 3. force state interventions into local authoritarian enclaves. Examples: 1. elections, mass parties and state power in Malaysia; communist threat, competitive elections and voter registration in Indonesia; 3. elections, rebellions and the temporary taming of rural oligarchs in the Philippines.


# State Breakdowns and Social Revolutions

## @Skocpol1979 State and Social Revolution

**Author** Theda Skocpol

**Year** 1979

French, Russia and Chinese Revolution

Skocpol asserts that Social Revolutions are rapid and basic transformations of a society's state and class structures. This is different from, for example, a mere 'rebellion' which merely involves a revolt of subordinate classes but may not create structural change and from a Political Revolution that may change state structures but not social structures. Industrialization can transform social structure but not change the political structure. What is unique about Social Revolutions, she says, is that basic changes in social structure and political structure occur in a mutually reinforcing fashion and these changes occur through intense sociopolitical conflict.

Skocpol explains social revolutions as being based on four factors: 1) state social structures, 2) international competitive pressures and 3) international demonstration effects, and 4) class relations. Her argument is influenced by the Marxist notion of the class struggle, but she differs from Marx as she sees the state as an autonomous actor within society. Her argument is even more powered by the structuralist argument that revolution is a dysfunctional response to a destabilization of social system) schools. The book is also state centric (as shown by the very title of the book). By analyzing how the social institution of the state changed and influenced the social change, the book can also be placed within the historical institutionalism paradigm.

She stresses that international-scale actions (like threats or outcomes of war, and political and economic inequalities) have a major effect on domestic events (like revolutions). This effect can be explained as the outside effects lead to increased destabilization and political crises (financial crisis, elite divisions, mobilization of groups sensing political opportunity) which in turn increases the likelihood that revolutionary forces will arise and act. Skocpol notes that while elites are important, ordinary citizens are also vital, as supported by the fact that most successful revolutions were aided by urban and peasants mobilizations.


## John Dunn 1982 Understanding Revolutions

A review work of Theda Skocpol the States and Social Revolutions

the role of state power in the reproduction of society

## Barrington Moore 1966 Social Origins of Democracy and Dictatorship

Barrington Moore's classic study seeks to understand the role of landed upper classes and peasants in the makings of capitalist democracy, fascism, and communism as distinct paths to modernity. Unavoidably, the book leads him to explore the role of commercial agriculture and urban classes as key factors in determining the various political outcomes in the following contexts: eighteenth century England and France, the U.S. Civil War, revolutionary China, fascist Japan, and post-colonial India. He finds that breaking the power of landed agrarian elites is key for the rise of democratic regimes.


## Moore, Skocpol, Rueschemeyer, Stevens and Stevens,; Therborn and Luebbert 

Moore thesis: No Bourgeoise, No democracy. is the bourgeoisie sufficiently strong to pull down the structures of feudal society? Yes -- libearal democracy; No -- can moderanization be achieved by means of 'revolution from above' (a labor repressive alliance) or the revulation from bottom (the peasant revolution lead to consolidation of power by a modernizing revolutionary elite). 


Gregory Luebbert 1991 liberalism, Facism and Social Democracy: whether or not succefful in incorporating the working class -- yes: interwar liberalism; no -- political regulation of capital-labor relationship required. whether the organized working class attempt to organize the rural poor -- yes facism (on the basis of an alliance of urban middle class and family farmers) -- no social democracy, on the basis of an alliance of the working class and the family farmers. 

Rueschemeyer, Stevens and Stevens, 1992 Capaitalist Development and Democracy
working class, the automous role of the state in the global economy market. 



## Dan Slater and Nicholas Rush Smith 2016 The Power of Counterrevolution

Elititist Origins of Political Order in postcolonial Asia and Africa

Counterrevolutions are collective and reactive efforts to defend the status quo, and its varied range of dominant elites against a credible threat to overturn them from below. 

The goal is to explain the stability of party dominance. Conterrevolutions can produce exceedingly durable, although not invincible political parties.



## Ted Gurr 1970 Why Men Rebel

In this book, Gurr examines the psychological frustration-aggression theory which argues that the primary source of the human capacity for violence is the frustration-aggression mechanism. Frustration does not necessarily lead to violence, Gurr says, but when it is sufficiently prolonged and sharply felt, it often does result in anger and eventually violence.

Gurr explains this hypothesis with his term "relative deprivation," which is the discrepancy between what people think they deserve, and what they actually think they can get. Gurr's hypothesis, which forms the foundation of the book, is that: "The potential for collective violence varies strongly with the intensity and scope of relative deprivation among members of a collectivity."(p.24)

It is noteworthy that Gurr does not look to a more absolute or objective indicator of deprivation as the source of political violence. People can become inured to a bad state of affairs, even one that offers so little access to life-sustaining resources that members of the group are starving or dying of remediable diseases or exposure.

If, however, there is a significant discrepancy between what they think they deserve and what they think they will get, there is a likelihood of rebellion. Gurr posits this to be the case even if there is no question that their basic needs will be met. The first situation may be a desperate one, but it is the second that is frustrating. And, according to Gurr, just as frustration produces aggressive behavior on the part of an individual, so too does relative deprivation predict collective violence by social groups.

## Jack A. Goldstone 2003 Comparative Historical Analysis and Knowledge Accumulation in the Study of Revolutions

CHA has a Bayesian style by heart. 

* Revolution from the modernization perspective: from traditional society to the modern society; Tilly (1978) argues for the emergence of organized contenders (crucial for the occurance of revolution); Moore (1966) captalist elites

* Social structure theory and its critics: Theda Skocpol 1979: international society and the world system;economic or political elites who had power to resist state-led reforms and create a political crisis; organziations that were capable of mobilizing peasants for popular uprisings against local authoriaties  

* Development after Skocpol: rational choice and game theory, collective action, the role of ideology playing as the glue for mobilization and collective action. 

* Knowledge accumulation of revolution: 1. conjuctural causations: there is no signle universal explanations for revolution. Some agreed conditions for revolutions: 1. a crisis of state authority in which the state is widely perceived by elites and popular groups as both ineffective and unjust 2. a crisis of elite relationships in which elites become divided, alienated, and polarized into factions that disagree over how to reconstitute state authority 3. a crisis of popular welfare in which urban and or rural groups find it difficult to maintain their customary standard or living through accustomed means; 4. the emergence of an elite-popular coalition to attack the authority of the state 5. an ideology of opposition that binds elites and popular groups in their attack on the authorities, justifies the attack and suggests alternative bases for authority. //// variaety of processes and outcomes 



## James Scott 1985 Weapons of the Weak, Everyday From of Resistence

Scott introduces the idea that oppression and resistance are in constant flux, and that by focusing (as political scientists often do) on visible historic 'events' such as organised rebellions or collective action we can easily miss subtle but powerful forms of 'every day resistance'. Scott looks at peasant and slave societies and their ways of responding to domination, with a focus not on observable acts of rebellion but on forms of cultural resistance and non-cooperation that are employed over time through the course of persistent servitude.

Scott’s research finds that overt peasant rebellions are actually rather uncommon, do not occur when and where expected, and often don’t have much impact.  Rather than seeing 'resistance as organisation', Scott looks at less visible, every-day forms of resistance such as 'foot-dragging, evasion, false compliance, pilfering, feigned ignorance, slander and sabotage'.  He finds these in rural and factory settings, and also among the middle class and elites (e.g. through tax evasion or conscription), but particularly among rural people who are physically dispersed and less politically organised than urban populations (Scott 1985).

## Steven Solnick 1996 The Breakdown of Hierachies in the Soviet Union and China

Question: why decentralization causes regime breakdown in Soviet Union but not in China?

The principal-agent problems exists in both countries. But China's cenrtal gov. never lost control over the local government, by creating quasi-ownership companies. In the Soviet cases, the rapid privatation increases the local autonomy and the creates incentives to sucede from the central gov. 

The problem of hidden action and hidden information: hidden action: how honestly the agent is working; to what the maximum output level is, given random factors and the agent's strcutural constraints. 



# Democracy and Transitions

## Rueschemeyer, Stephens and Stephens 1992 Capitalist Development and Democracy

the class-structural model of democratic transition; very similar to Moore's frame, adding working class into analysis. Capatalism is essential to democracy as it weakens the landed upper class and strengthens the owrking class and other subordinate classes. 



## Linz and Stephens 1995 Problems of Democratic Transition and Consolidation

Salient differences in the pre-transition regime and the nature of the transition that have direct consequences for the nature and durability of the ensuing democratic experiment. The first part of the book provides the theoretical underpinning and subsequent sections contain a wide range of case studies on individual country experiences.

The first step in this task is identifying the important characteristics of their dependent variable, namely a consolidated democracy. They delineate five 'arenas': civil society, political society, rule of law, bureaucratic structure, and economic society. First, a vibrant civil society provides a check on state power. Second, political society involves the arrangements through which contests for political power are legitimately arranged. Third, a set of explicit rules to which all are bound is another precondition for democratic consolidation. Fourth, a democratic government requires an effective bureaucratic apparatus to maintain the monopoly of violence and to enforce law. In a subsequent chapter, Linz and Stepan further elaborate on the question of nationalism and the under-explored problem of 'stateness' for democratic consolidation. Finally, a socially agreed-upon set of practices to mediate between state and market are crucial for democracy.

Further, they find it useful to distinguish four additional regime types: authoritarianism, totalitarianism, post-totalitarianism, and sultanism. Post-totalitarianism characterized a number of parts of the former Soviet bloc after Stalin and became more common the closer one gets to the fall of the Soviet Union. These different regime types have consequences for the paths of democratic transition that are possible. One common path of democratization has been through pacted transitions. This is a common path for authoritarian and post-totalitarian regimes. However, totalitarian or sultanic systems place such severe restraints on political and social space that it is unlikely an opposition could develop that would be significant enough to compel the regime to negotiate. Similarly, in both of these contexts, losing a war is unlikely to provide a democratic opening unless outside powers invest heavily in building a democracy. If elections are not held quickly, interim governments may be tempted to remain in power in the aftermath of sultanism or authoritarianism. Former authoritarian governments that were composed of a hierarchical military organization may be more willing to extricate themselves from power peacefully if the institution of the military is respected. In a non-heirarchical military, by contrast, infighting may make it easier to realize civilian oversight, but different factions may have different agendas and destabilize the situation.

To bring all these components together, the legacy regime type influences the prospects for each of the five arenas. Of the four non-democratic regime types, authoritarianism has the best chance of having a tradition of rule of law to build upon. In terms of building political society, all have weaknesses. Totalitarian and post-totalitarian require the dismantling of the dominant party's position and in sultanic and authoritarian situations, trust and institutions must often be built. Although constitutions have often existed in these contexts, they typically have negative connotations for the public so there is a need for significant overhaul if not complete abandonment of existing arrangements. After authoritarian regimes, by contrast, there may be a pre-authoritarian constitution that could be revived or frequently the constitution from the authoritarian period is modified. Comparatively speaking, bureaucracies held over from authoritarian regimes may provide a sufficient foundation to build upon. In totalitarian and post-totalitarian contexts, however, the intertwining of party and bureaucracy necessitates significant reform. Under sultanism, the bureaucracy is likely riddled with corruption. Finally, under authoritarianism, there may be a reasonable amount of autonomy for economic actors that can allow for pluralism in the civic, political, and economic societies. By contrast, the command economy and patrimonialism in totalitarian and sultanistic regimes require much more dramatic reform.


## O'Donnell and Schmitter 1986 Transitions from authoritarian Rule Tentative Conclusions about Uncertain Democracies

Undervalue the structural stuffs. -- unexpected events, insufficient information, plasticity and even identification of political identities, as well as the talents of specific individuals are frequently decisive in determing outcomes. Behaviorist approach, individual-level interactions are crucial for outcomes.

An interaction between authoritarian hard liners and soft liners. 


## James Mahoney 2003 Knowledge Accumulation in Comparative Historical Research

Knowledge accumulation Cases of democracy and authoritarianism

Descriptive findings, causal findings (testing and elaboration), methodologies and meta-theories. 





## Levitsky and Way 2010 Competitive Authoritariansim 




## Svolik 2012 Politics of Authoritarian Rule

All authoritarian regimes must resolve two fundamental conflicts. First, dictators face threats from the masses over which they rule - this is the problem of authoritarian control. A second, separate challenge arises from the elites with whom dictators rule - this is the problem of authoritarian power-sharing. Crucially, whether and how dictators resolve these two problems is shaped by the dismal environment in which authoritarian politics takes place: in a dictatorship, no independent authority has the power to enforce agreements among key actors and violence is the ultimate arbiter of conflic

## Haggard and Kaufman 1995 Political Economy of Democratic Transitions
Under economic crisis, the divisions within authoritarian regime and the defection of the key elites are crucial impetus for demcoratization.  


## Acemoglu and Robinson 2005


## Carles Boix 2003 Democracy and Redistribution 



## Ross 2001

rentier state effect, repression effect, modernization effect




# Institutions

## Kathleen Thelen 2003 How Institutions Evolve

Two different approaches of institutional changes: constant causes -- it cam come in several varieties, such as functionalist, political and cultural, but all would suggest that the same factors that account for the genesis of an institution will also explain institutional change over time. Path dependence theory suggests that institutions may outlive the forces that brought them into being, the factors responsible for the reproduction of an institution may be quite different from those that account for the existence of the institution in the first place.

1.a functionalist: instituion as a solution of colletive action problems, reducing uncertainty, providing focal points, decrease transactional costs etc. 

1.b power distributional accounts: institutions as arrangements of power and resource, social institutions reflect power asymmetries. institutions forge out of political conflicts.

1.c cultural-sociological approach: instituions reflect the shared cultural understandings of what is efficient, or moral, or modern. 

2. path-dependence: numerous causes of instituional development and changes. critical junctures and historical junctures. 




# Political Parties



# Citizen-government relationship




# Welfare state and Political Economy




# Principal-Agent Problem
 
## Bueno de Mesquita et al. 2003 The Logic of Political Survival 

In selectorate theory, three groups of people affect leaders. These groups are the nominal selectorate, the real selectorate, and the winning coalition. The nominal selectorate, also referred to as the interchangeables, includes every person who has some say in choosing the leader (for example, in an American presidential election, all registered voters). The real selectorate, also referred to as the influentials, are those who really choose the leaders (for example, in an American presidential election, those people who cast a vote). The winning coalition, also referred to as the essentials, are those whose support translates into victory (for example, in an American presidential election, those voters that get a candidate to 270 Electoral College votes). In other countries, leaders may stay in power with the support of much smaller numbers of people, such as senior figures in the security forces, and business oligarchs, in contemporary Russia.

The fundamental premise in selectorate theory is that the primary goal of a leader is to remain in power. To remain in power, leaders must maintain their winning coalition. When the winning coalition is small, as in autocracies, the leader will tend to use private goods to satisfy the coalition. When the winning coalition is large, as in democracies, the leader will tend to use public goods to satisfy the coalition.